"""Markdown template for the regenerated .sdd/agent-instructions.md file."""

from __future__ import annotations


def build_agent_instructions_content(
    fingerprint: str,
    generated_at: str,
    mandate_count: int,
    ids_preview: str,
    mandates_list: str,
) -> str:
    """Return the full .sdd/agent-instructions.md content."""
    return f"""# SDD Agent Instructions — Authority & Bootstrap
# Regenerated by: sdd governance generate
# Governance fingerprint: {fingerprint}
# Active mandates: {mandate_count}{" (" + ids_preview + ")" if ids_preview else ""}
# Regenerated at: {generated_at}

**This workspace is governed by Spec Driven Development (SDD).**

---

## 1. Authority Hierarchy

**The source of truth for all governance is `.sdd/`.**

```
.sdd/
├── metadata.json              ← Workspace version + fingerprints
├── agent-instructions.md      ← THIS FILE
└── source/
    ├── mandates/mandates.md   ← Mandate descriptions
    └── README.md
```

---

## 2. Mandatory Bootstrap

Before planning, coding, or deciding:

1. **Read `.sdd/metadata.json`** — check version, fingerprint, mandate count
2. **Read `.sdd/metadata.json`** — extract mandate IDs and titles
3. **Read `.sdd/source/mandates/mandates.md`** — understand enforcement rules

---

## 3. Active Mandates

{mandates_list}

---

## 4. Pre-Task Checklist

- [ ] `.sdd/metadata.json` read → version, fingerprint, count verified
- [ ] `.sdd/metadata.json` read → mandates extracted
- [ ] `.sdd/source/mandates/mandates.md` read → enforcement rules understood

---

## 5. Fingerprint Integrity Check

**Fingerprint this version:** `{fingerprint}`
**Regenerated at:** {generated_at}

Verify bootstrap integrity:
1. Compare fingerprint in your bootstrap file (CLAUDE.md, GEMINI.md, etc.)
2. Compare with `.sdd/metadata.json` → field `governance_fingerprint`
3. If they differ → run `sdd governance generate` to sync

---

## Governance Mode

When operating under SDD via a skill or CLI entry point (`sdd ask`, `sdd-ask`, `sdd-converge`, etc.),
the execution context is **HARD governance mode**.

| Entry point | Mode |
|-------------|------|
| `sdd ask` / `sdd-ask` skill | HARD |
| `sdd-converge`, `sdd-correct`, `sdd-stabilize` | HARD |
| Direct API / notebook / ad-hoc | SOFT |

### HARD Mode Rules

**Rule 1 — Execution gate:**
If `sdd ask` output contains `execution_gate: blocked`, **STOP immediately**.
Report the `gate_reason` to the user. Do not proceed with any action until the user re-authorizes.

**Rule 2 — Git authorization:**
Git state-modifying commands (`add`, `commit`, `push`, `reset`, `merge`, `rebase`, etc.)
are **blocked** unless the current user message contains explicit authorization.
Task completion is NOT authorization. Only explicit phrases like "commit this", "push to remote",
"run git add and commit" constitute authorization.

**Rule 3 — `intake_index_mode: none` is an independent signal, not "the gate":**
`intake_index_mode: none` means no governance context was indexed for this query.
This is **separate from Rule 1** — `execution_gate` may be `allowed` while
`intake_index_mode` is still `none` (e.g. for short queries). Surface this
condition to the user by name and value — do not describe it as "the gate is
blocked" unless `execution_gate: blocked` is also present. Then stop and wait for
the user to decide how to continue.

---

## 7. Fallback & Escalation

If `.sdd/` is incomplete or inconsistent:
- **STOP EXECUTION IMMEDIATELY. Do not guess or interpolate.**
- Escalate to human with specific problem description
- You must refuse to bypass the governance gate.
"""
