"""Markdown template for the regenerated .sdd/agent-instructions.md file."""

from __future__ import annotations

from sdd_wizard.templates._hard_mode_rules import HARD_MODE_RULES_SECTION


def build_agent_instructions_content(
    fingerprint: str,
    generated_at: str,
    mandate_count: int,
    ids_preview: str,
    mandates_list: str,
) -> str:
    """Return the full .sdd/agent-instructions.md content."""
    return f"""# SDD Agent Instructions — Authority & Bootstrap
# Regenerated by: sdd governance generate
# Governance fingerprint: {fingerprint}
# Active mandates: {mandate_count}{" (" + ids_preview + ")" if ids_preview else ""}
# Regenerated at: {generated_at}

**This workspace is governed by Spec Driven Development (SDD).**

---

## 1. Authority Hierarchy

**The source of truth for all governance is `.sdd/`.**

```
.sdd/
├── metadata.json              ← Workspace version + fingerprints
├── agent-instructions.md      ← THIS FILE
└── source/
    ├── mandates/mandates.md   ← Mandate descriptions
    └── README.md
```

---

## 2. Mandatory Bootstrap

Before planning, coding, or deciding:

1. **Read `.sdd/metadata.json`** — check version, fingerprint, mandate count
2. **Read `.sdd/metadata.json`** — extract mandate IDs and titles
3. **Read `.sdd/source/mandates/mandates.md`** — understand enforcement rules

---

## 3. Active Mandates

{mandates_list}

---

## 4. Pre-Task Checklist

- [ ] `.sdd/metadata.json` read → version, fingerprint, count verified
- [ ] `.sdd/metadata.json` read → mandates extracted
- [ ] `.sdd/source/mandates/mandates.md` read → enforcement rules understood

---

## 5. Fingerprint Integrity Check

**Fingerprint this version:** `{fingerprint}`
**Regenerated at:** {generated_at}

Verify bootstrap integrity:
1. Compare fingerprint in your bootstrap file (CLAUDE.md, GEMINI.md, etc.)
2. Compare with `.sdd/metadata.json` → field `governance_fingerprint`
3. If they differ → run `sdd governance generate` to sync

---

{HARD_MODE_RULES_SECTION}

---

## 7. Fallback & Escalation

If `.sdd/` is incomplete or inconsistent:
- **STOP EXECUTION IMMEDIATELY. Do not guess or interpolate.**
- Escalate to human with specific problem description
- You must refuse to bypass the governance gate.
"""
