"""Template strings and content builders for AISeedsGenerator."""

from __future__ import annotations

CLAUDE_BOOTSTRAP_SCRIPT = """#!/usr/bin/env sh
set -eu

if [ ! -f ".sdd/metadata.json" ]; then
  echo "[sdd-bootstrap] missing .sdd/metadata.json"
  exit 0
fi

if command -v sdd >/dev/null 2>&1; then
  sdd bootstrap run --session-guard-hours 4 >/dev/null 2>&1 || true
fi
"""

CLAUDE_SETTINGS = """{
  "hooks": {
    "PreToolUse": [
      {
        "matcher": ".*",
        "hooks": [
          {
            "type": "command",
            "command": ".claude/sdd-bootstrap.sh"
          }
        ]
      }
    ]
  }
}
"""


def build_copilot_instructions(fp_header: str) -> str:
    return f"""# GitHub Copilot Governance Bootstrap
{fp_header}

You are operating in a workspace governed by **Spec Driven Development (SDD)**.

## Entrypoint Contract

1. You must learn commands and skills from your custom folder path:
   - `.github/prompts/`
2. You are under governance. Always resolve instructions from `.sdd`.
   Initial reference:
   - `.sdd/agent-instructions.md`

## Commands And Skills (Source Of Truth)

1. Commands source of truth: `.sdd/commands`.
2. Skills source of truth: `.sdd/skills`.
3. On startup, load:
   - `.sdd/commands/registry.json`
   - `.sdd/skills/registry.json`
4. For each active command/skill in registries, read canonical files:
   - Commands: `.sdd/commands/<command-id>/command.yaml`
   - Skills: `.sdd/skills/<skill-name>/skill.yaml`
5. Precedence rule:
   - Local path (`.github/prompts/*`) is for context and ergonomics.
   - `.sdd` is authoritative for routing/policy and wins conflicts.

## Critical Instruction

Read and adhere to the canonical governance rules in:
```
.sdd/agent-instructions.md
```

This file is the **single source of truth** for all governance policies in this workspace.

## Quick Reference

- **Mandate enforcement**: Non-negotiable rules (M001-M010, M015)
- **Governance status**: Run `sdd runtime status` to check workspace health
- **Validation**: Run `sdd governance validate` before finalizing changes
- **Activation**: Governance activates automatically on project load via `.sdd/seedlings/`

## Governance Documentation

All governance documentation lives in `.sdd/source/`:
- `mandates/mandates.md` — Mandate descriptions and enforcement rules
- `guidelines/` — Customizable guidelines by category (if any)
- `README.md` — Onboarding guide for agents

## Operating Rules

- Do not bypass mandatory mandates.
- Prefer generated templates and `.sdd/*` canonical governance over improvised structure.
- When the workspace state is unclear, run `sdd runtime status` first.

## Expected Validation Commands

```bash
sdd governance validate
sdd runtime status
```

## Notes

This bootstrap is intentionally a redirector. Do not rely on framework-external paths.

## Safe Fallback

If registries or canonical files are missing/inconsistent, register bootstrap drift and continue in safe fallback mode without inventing missing rules.
"""


def build_claude_md(fp_header: str) -> str:
    return f"""# CLAUDE.md
# Generated by: sdd governance generate
# Version: 3.0
{fp_header}

## ⚠️ CRITICAL: Governance Source of Truth

**This Claude workspace is governed by `.sdd/` (Spec Driven Development artifacts).**

## Entrypoint Contract

1. You must learn commands and skills from your custom folder path:
   - `.claude/commands/`
   - `CLAUDE.md`
2. You are under governance. Always resolve instructions from `.sdd`.
   Initial reference:
   - `.sdd/agent-instructions.md`

## Commands And Skills (Source Of Truth)

1. Commands source of truth: `.sdd/commands`.
2. Skills source of truth: `.sdd/skills`.
3. On startup, load:
   - `.sdd/commands/registry.json`
   - `.sdd/skills/registry.json`
4. For each active command/skill in registries, read canonical files:
   - Commands: `.sdd/commands/<command-id>/command.yaml`
   - Skills: `.sdd/skills/<skill-name>/skill.yaml`
5. Precedence rule:
   - Local path (`.claude/*`, `CLAUDE.md`) is for context and ergonomics.
   - `.sdd` is authoritative for routing/policy and wins conflicts.

**You MUST read `.sdd/agent-instructions.md` BEFORE any other action.**

No other file overrides or extends the governance in `.sdd/`. Everything you need is there.

---

## Quick Reference

| File | Purpose |
|------|---------|
| `.sdd/agent-instructions.md` | **START HERE** — Complete agent bootstrap instructions |
| `.sdd/metadata.json` | Workspace version, fingerprints, item counts |
| `.sdd/metadata.json` | Human-readable mandates snapshot |
| `.sdd/source/mandates/mandates.md` | Full mandate descriptions with enforcement rules |

---

## One Rule

**Before planning, coding, or deciding:** read `.sdd/agent-instructions.md`.

If that file says something different from what you remember seeing in CLAUDE.md, **trust `.sdd/agent-instructions.md` — it is authoritative.**

---

## Safe Fallback

If registries or canonical files are missing/inconsistent, register bootstrap drift and continue in safe fallback mode without inventing missing rules.
"""
