""".sdd/runtime/README.md sections: cache invalidation, optimization tips,
troubleshooting, best practices, metrics, and footer. Split out of
_runtime_readme_template.py to keep files under the 200-line convention.
"""

from __future__ import annotations


def _cache_invalidation_section() -> str:
    return """## Cache Invalidation

Re-read governance from `.sdd/source/` if:

1. **Manual update**: Files are explicitly updated by developer
2. **Time-based**: Cache expires (e.g., 24 hours)
3. **Version change**: Metadata indicates version change
4. **Explicit refresh**: Agent receives refresh command

Example cache validity check:

```python
def should_refresh_cache(agent):
    last_update = agent.memory.get('governance_updated')
    current_time = time.time()

    # Refresh if older than 24 hours or no timestamp
    cache_age = current_time - (last_update or 0)
    return cache_age > 86400
```

"""


def _optimization_tips_section() -> str:
    return """## Optimization Tips

### 1. Lazy Loading (For Large Governance)

Don't load all guidelines at once. Load on demand:

```python
def get_guideline(category):
    if category not in agent.memory.get('guidelines', {}):
        path = Path('.sdd/source/guidelines') / f'{category}.md'
        agent.memory['guidelines'][category] = path.read_text()
    return agent.memory['guidelines'][category]
```

### 2. Compression (For Token Efficiency)

Compress guidelines before caching:

```python
import gzip
import base64

def compress_guideline(content):
    compressed = gzip.compress(content.encode())
    return base64.b64encode(compressed).decode()

def decompress_guideline(encoded):
    compressed = base64.b64decode(encoded)
    return gzip.decompress(compressed).decode()
```

### 3. Summarization (For Context Window)

Create summaries instead of full files:

```python
# For each guideline, create a 1-paragraph summary
summaries = {
    'git': 'Use conventional commits, protect main, PR reviews required, ...',
    'testing': 'Write tests first, >80% coverage required, run CI on all PRs, ...',
    ...
}
```

"""


def _troubleshooting_section() -> str:
    return """## Troubleshooting

### Issue: Agent doesn't follow governance

**Solution**: Verify cache was loaded and is up-to-date
```python
print(agent.memory.get('governance_updated'))  # noqa: T201
print(len(agent.memory.get('mandates', '')))  # noqa: T201
```

### Issue: Out of memory with large governance

**Solution**: Use lazy loading or compression (see Optimization Tips)

### Issue: Stale governance after updates

**Solution**: Implement cache invalidation based on file mtime
```python
governance_mtime = Path('.sdd/source/mandates/mandates.md').stat().st_mtime
if governance_mtime > agent.memory.get('governance_loaded_at', 0):
    refresh_cache()
```

"""


def _best_practices_and_footer_section() -> str:
    return """## Best Practices

1. ✅ **Load once per session** - Don't re-read governance files repeatedly
2. ✅ **Cache in memory** - Keep governance in agent context/memory
3. ✅ **Reference by category** - Use structured memory keys
4. ✅ **Implement cache invalidation** - Refresh on updates
5. ✅ **Monitor cache size** - Warn if governance grows too large
6. ✅ **Document cache strategy** - Clarify to team how governance is cached

## Metrics to Track

- Cache hit rate (% of requests using cached vs fresh)
- Average token savings per session
- Cache refresh frequency
- Cache size in memory

---

**Generated by SDD Wizard v3.0**
"""
