"""Contract models and helpers for SDD integration."""

from sdd_integration.contracts.external_contract_v1 import (
    CONTRACT_VERSION_V1,
    NarrativeChannel,
    NarrativeContractError,
    NarrativeDomain,
    NarrativeMode,
    NarrativeOutcome,
    NarrativePolicy,
    NarrativeRequestEnvelope,
    NarrativeRequestInput,
    NarrativeResponseEnvelope,
    NarrativeResponseResult,
    NarrativeTelemetry,
    build_request_envelope,
    build_response_envelope,
    choose_execution_path,
    resolve_fallback_outcome,
    validate_request_compatibility,
    validate_response_matches_request,
)
from sdd_integration.contracts.transport_resolution import (
    TransportActivationMode,
    TransportChannel,
    TransportResolutionError,
    build_transport_aware_request_envelope,
    is_claude_code_context,
    resolve_transport_activation_summary,
    resolve_transport_channel,
)

__all__ = [
    "CONTRACT_VERSION_V1",
    "NarrativeChannel",
    "NarrativeContractError",
    "NarrativeDomain",
    "NarrativeMode",
    "NarrativeOutcome",
    "NarrativePolicy",
    "NarrativeRequestEnvelope",
    "NarrativeRequestInput",
    "NarrativeResponseEnvelope",
    "NarrativeResponseResult",
    "NarrativeTelemetry",
    "TransportActivationMode",
    "TransportChannel",
    "TransportResolutionError",
    "build_transport_aware_request_envelope",
    "is_claude_code_context",
    "build_request_envelope",
    "build_response_envelope",
    "choose_execution_path",
    "resolve_fallback_outcome",
    "resolve_transport_activation_summary",
    "resolve_transport_channel",
    "validate_request_compatibility",
    "validate_response_matches_request",
]
