#!/bin/sh
# Generated by sdd_adapters DevinPluginGenerator. Do not edit by hand.
cat <<'JSON'
{"hookSpecificOutput": {"hookEventName": "SessionStart", "additionalContext": "SDD GOVERNANCE PROJECTION (devin) | profile=soft | policy_source=embedded_snapshot | assurance=reduced | external_dependencies=none | plugin_version={{ plugin_version }} | policy_digest={{ policy_digest }}"}}
JSON
