from pathlib import Path

from sdd_integration.builders.governance.pipeline_builder import PipelineBuilder
from sdd_wizard.validator import SourceValidator


def test_validate_mandate_spec_accepts_block_format() -> None:
    mandate_text = """mandate M001 {
  type: \"MANDATE\"
  title: \"Clean Architecture\"
  description: \"Clean Architecture\"
  category: \"features\"
  rationale: \"Derived from spec/canonical/features/CLEAN_ARCHITECTURE.md\"
}
"""

    result = SourceValidator.validate_mandate_spec(mandate_text)

    assert result["valid"] is True
    assert result["statistics"]["mandate_count"] == 1
    assert result["statistics"]["mandates"][0]["id"] == "M001"
    assert result["statistics"]["mandates"][0]["title"] == "Clean Architecture"


def test_pipeline_builder_parses_block_mandate_spec_with_empty_guidelines(
    tmp_path: Path,
) -> None:
    (tmp_path / "mandate.spec").write_text(
        """mandate M001 {
  type: \"MANDATE\"
  title: \"Clean Architecture\"
  description: \"Clean Architecture\"
  category: \"features\"
}
""",
        encoding="utf-8",
    )
    (tmp_path / "guidelines.dsl").write_text(
        "# Generated by sdd docs update\n", encoding="utf-8"
    )

    result = PipelineBuilder(str(tmp_path)).build()

    assert len(result["core_items"]) == 1
    assert len(result["client_items"]) == 0
    assert result["governance_core"]["fingerprint"] != "empty"


def test_pipeline_builder_parses_compact_mandate_spec_format(tmp_path: Path) -> None:
    (tmp_path / "mandate.spec").write_text(
        "\n".join(
            [
                "M002: Domain Boundaries",
                "M001: Clean Architecture",
                "M002: Domain Boundaries",
            ]
        ),
        encoding="utf-8",
    )
    (tmp_path / "guidelines.dsl").write_text("", encoding="utf-8")

    result = PipelineBuilder(str(tmp_path)).build()
    core_ids = [item["id"] for item in result["core_items"]]

    assert core_ids == ["M001", "M002"]
    assert result["governance_core"]["fingerprint"] != "empty"


def test_pipeline_builder_parses_bracket_mandate_spec_format(tmp_path: Path) -> None:
    (tmp_path / "mandate.spec").write_text(
        "\n".join(
            [
                "- [M010] Keep adapters isolated",
                "- [M011] No direct interface dependency",
            ]
        ),
        encoding="utf-8",
    )
    (tmp_path / "guidelines.dsl").write_text("", encoding="utf-8")

    result = PipelineBuilder(str(tmp_path)).build()
    core_ids = [item["id"] for item in result["core_items"]]

    assert core_ids == ["M010", "M011"]
