from __future__ import annotations

UNIVERSAL_LANGUAGE_GUIDELINES = """# Generated by SourceSpecBootstrapper

guideline G01 {
  type: HARD
  title: "Dependency Direction — Python"
  description: "Domain and application layers must not import infrastructure adapters or framework code directly. Use import-linter to enforce layer boundaries."
  category: architecture
}

guideline G02 {
  type: HARD
  title: "Dependency Direction — Go"
  description: "Domain and application packages must not import infrastructure adapters or external clients. Use golangci-lint with depguard to enforce boundaries."
  category: architecture
}

guideline G03 {
  type: HARD
  title: "Dependency Direction — Java"
  description: "Domain and application classes must not depend on infrastructure adapters, frameworks, or persistence providers directly. Use ArchUnit to enforce layer boundaries in CI."
  category: architecture
}

guideline G04 {
  type: HARD
  title: "Dependency Direction — Node.js / TypeScript"
  description: "Domain and application modules must not import infrastructure adapters, database clients, or framework code directly. Use ESLint import rules and tsc strict mode to enforce boundaries."
  category: architecture
}

guideline G05 {
  type: SOFT
  title: "Code Style — Python"
  description: "Python projects must use ruff for linting and formatting, mypy for type checking. No bare except, no Any-driven development, no import-time side effects. All public functions must be type-annotated. Use Protocol for contracts, typed models for structured data."
  category: code_quality
  mandate_ref: M018
}

guideline G06 {
  type: SOFT
  title: "Code Style — Go"
  description: "Go projects must use gofmt for formatting and golangci-lint for static analysis. All errors must be checked and wrapped with context. No panic as control flow for expected errors. No goroutine leaks — every goroutine must have a cancellation path via context.Context."
  category: code_quality
  mandate_ref: M018
}

guideline G07 {
  type: SOFT
  title: "Code Style — Java"
  description: "Java projects must use Checkstyle and PMD for static analysis. Business logic must not live in controllers. Domain classes must not depend on Spring annotations or JPA in the domain layer. Exceptions must be caught specifically and cause preserved."
  category: code_quality
  mandate_ref: M018
}

guideline G08 {
  type: SOFT
  title: "Code Style — TypeScript"
  description: "TypeScript projects must enable strict mode. No any escape hatches. Promises must be awaited or explicitly fire-and-forget with .catch. Business logic must not live in route handlers. External JSON must be validated before casting to domain types."
  category: code_quality
  mandate_ref: M018
}

guideline G09 {
  type: HARD
  title: "Anti-Patterns — Python"
  description: "Python-specific anti-patterns that block merge: bare except, Any-driven development, monkeypatch architecture (compensating for poor dependency injection), import-time side effects. All errors must be caught specifically and re-raised with context using raise ... from exc."
  category: code_quality
  mandate_ref: M001
}

guideline G10 {
  type: HARD
  title: "Anti-Patterns — Go"
  description: "Go-specific anti-patterns that block merge: ignored errors (using _ = err without documented reason), panic as control flow for expected application errors, goroutine leaks (goroutines started without cancellation path), package dumping grounds (internal/common or internal/utils with unrelated responsibilities)."
  category: code_quality
  mandate_ref: M001
}

guideline G11 {
  type: HARD
  title: "Anti-Patterns — Java"
  description: "Java-specific anti-patterns that block merge: business logic in controllers, framework-coupled domain (Spring or JPA annotations in domain classes), exception swallowing (empty catch blocks), over-engineered inheritance (deep hierarchy where composition would suffice)."
  category: code_quality
  mandate_ref: M001
}

guideline G12 {
  type: HARD
  title: "Anti-Patterns — TypeScript"
  description: "TypeScript-specific anti-patterns that block merge: any escape hatch (using any to silence compiler), floating promises (unhandled async failures), business logic in route handlers, unsafe type assertion (casting external JSON directly to domain types without runtime validation)."
  category: code_quality
  mandate_ref: M001
}

guideline G13 {
  type: SOFT
  title: "Performance — Python"
  description: "Python performance must be evidence-based: profile before optimizing. Avoid unnecessary object creation in hot loops. Use generators for large sequences. Avoid repeated network or database calls — batch where possible. Cache only when invalidation is explicit. Use async I/O for I/O-bound workloads. Add benchmarks before and after non-trivial optimizations."
  category: performance
  mandate_ref: M018
}

guideline G14 {
  type: SOFT
  title: "Performance — Go"
  description: "Go performance must be measured with pprof before optimizing. Avoid unnecessary allocations in hot paths. Use sync.Pool for frequently allocated short-lived objects. Avoid goroutine spawning per request without pool. Benchmark with go test -bench and -benchmem."
  category: performance
  mandate_ref: M018
}

guideline G15 {
  type: SOFT
  title: "Performance — Java"
  description: "Java performance must be measured with JMH or profiler before optimizing. Use StringBuilder for string concatenation in loops. Avoid eager loading of large associations. Use connection pooling. Avoid String.format in hot paths."
  category: performance
  mandate_ref: M018
}

guideline G16 {
  type: SOFT
  title: "Performance — Node.js / TypeScript"
  description: "Node.js performance must be measured with profiler or clinic.js before optimizing. Avoid blocking the event loop with CPU-intensive synchronous work. Batch database queries instead of N+1. Avoid re-parsing JSON or re-creating regex in hot paths. Use worker threads for CPU-bound tasks."
  category: performance
  mandate_ref: M018
}

guideline G17 {
  type: SOFT
  title: "Project Structure — Python"
  description: "Python projects must follow src/ layout with domain/, application/, adapters/, infrastructure/ subdirectories. Tests mirror src/ under tests/. Module names reflect business capability, not technical role — avoid utils/, helpers/, common/."
  category: architecture
  mandate_ref: M018
}

guideline G18 {
  type: SOFT
  title: "Project Structure — Go"
  description: "Go projects must use cmd/ for entry points, internal/ for private packages. Domain logic in internal/domain/. Adapters in internal/adapters/. Ports in internal/ports/. Package names reflect cohesive behavior — avoid internal/common and internal/utils. No circular imports."
  category: architecture
  mandate_ref: M018
}

guideline G19 {
  type: SOFT
  title: "Project Structure — Java"
  description: "Java projects must follow a package hierarchy with layers: domain, application, adapters, infrastructure. Domain package must not import any other package except domain itself. Use Maven or Gradle standard layout: src/main/java, src/test/java."
  category: architecture
  mandate_ref: M018
}

guideline G20 {
  type: SOFT
  title: "Project Structure — TypeScript"
  description: "TypeScript projects must use src/ layout with domain/, application/, adapters/, infrastructure/ directories and path aliases @domain/*, @application/*, @adapters/*. tsconfig.json must enable strict mode. No barrel files (index.ts re-exporting everything) — they hide boundaries and slow compilation."
  category: architecture
  mandate_ref: M018
}

guideline G021 {
  type: SOFT
  title: "Language Preference Context — Interaction Surfaces"
  description: "User-declared language preference from the wizard should guide chat and operational UI surfaces when those surfaces are not persisted as technical documentation or governance artifacts."
  category: communication
  mandate_ref: M011
  examples: ["Wizard preference pt-BR -> agent chat and operational prompts may use pt-BR", "Persisted technical ADR in pt-BR -> VIOLATION because M011 still applies"]
}

guideline G022 {
  type: SOFT
  title: "Language Preference Context — Workspace-Local Notes"
  description: "Workspace-local notes and analysis artifacts may follow explicit user preference when the workspace classifies them as local documentation rather than canonical technical documentation."
  category: documentation
  mandate_ref: M011
  examples: [".analysis note in pt-BR with local-only intent -> CONTEXTUAL", "Canonical governance artifact in pt-BR -> VIOLATION because M011 still applies"]
}

guideline G023 {
  type: SOFT
  title: "Git Safety Practices"
  description: "Operational guidance for git command safety under M010 parallel-state assumption. Before any mutating action: run git status/diff first. Prefer direct file edits over git workflow commands. Do not stash, commit, cherry-pick, or push automatically — provide a summary and suggested commit message instead. Treat uncommitted work as potentially belonging to parallel agents or developers. Before any restricted command, state what it does, why it is needed, what state it may affect, and whether safer alternatives exist."
  category: governance
  mandate_ref: M010
  examples: ["After completing work: provide summary + suggested commit message, do not run git commit -> OK", "Before git stash: explain impact on parallel work, wait for approval -> OK", "git stash pop without asking -> VIOLATION", "git commit after task completion without explicit user instruction -> VIOLATION", "git status to inspect state before proposing action -> OK"]
}
"""
