"""Golden-output test for build_runtime_readme.

Guards the structure-refactor split of _runtime_readme_template.py into
_runtime_readme_integration_sections.py / _runtime_readme_maintenance_sections.py
(see .analysis/pending/wizard-structure-refactor-20260708/) — output must stay
byte-identical across the split.
"""

from __future__ import annotations

import pytest

from sdd_wizard.orchestration.writers._runtime_readme_template import (
    build_runtime_readme,
)

pytestmark = pytest.mark.unit

_ARGS: dict[str, str] = {
    "generated_at": "2026-07-08T12:00:00Z",
    "language_context_lines": "Interaction language: en-US.\n\n",
    "runtime_guideline_load_snippet": (
        "    guidelines = read_file('.sdd/source/guidelines/git.md')\n"
    ),
}


def test_build_runtime_readme_includes_all_sections() -> None:
    output = build_runtime_readme(**_ARGS)

    assert output.startswith("# .sdd/runtime - Agent Pre-Cache Strategy")
    assert output.rstrip().endswith("**Generated by SDD Wizard v3.0**")
    for heading in (
        "## Overview",
        "## Language Context",
        "## What is Pre-Caching?",
        "## Pre-Cache Workflow",
        "## Integration with Agent Frameworks",
        "## Memory Organization Strategy",
        "## Cache Invalidation",
        "## Optimization Tips",
        "## Troubleshooting",
        "## Best Practices",
        "## Metrics to Track",
    ):
        assert heading in output, f"missing section: {heading}"


def test_build_runtime_readme_interpolates_all_args() -> None:
    output = build_runtime_readme(**_ARGS)

    assert _ARGS["generated_at"] in output
    assert _ARGS["language_context_lines"] in output
    assert _ARGS["runtime_guideline_load_snippet"] in output


def test_build_runtime_readme_preserves_literal_braces_in_code_samples() -> None:
    """The template's Python code samples use literal `{...}` dict syntax —
    the split must not accidentally interpolate or mangle those braces.
    """
    output = build_runtime_readme(**_ARGS)
    assert "agent.memory = {" in output
    assert "self.governance = {}" in output


def test_build_runtime_readme_section_order_is_stable() -> None:
    output = build_runtime_readme(**_ARGS)
    headings = [
        "## Overview",
        "## Language Context",
        "## What is Pre-Caching?",
        "## Pre-Cache Workflow",
        "## Integration with Agent Frameworks",
        "## Memory Organization Strategy",
        "## Cache Invalidation",
        "## Optimization Tips",
        "## Troubleshooting",
        "## Best Practices",
        "## Metrics to Track",
    ]
    positions = [output.index(h) for h in headings]
    assert positions == sorted(positions)
