"""Golden-snapshot regression guard for root-seed bootstrap templates.

`CLAUDE.md`, `AGENTS.md`, and `GEMINI.md` are gitignored, per-workspace
artifacts regenerated by `generate_root_bootstrap_from_config()` (see
`sdd_wizard.orchestration.seedlings.governance_seeds`) — they embed a
`generated_at` timestamp, so their raw on-disk bytes are never a valid golden
target. What *is* stable and committable is the underlying template output:
`build_claude_md`, `render_agent_redirector`, and `build_agents_md` are pure
functions of (fingerprint, mandate_ids, generated_at, ...). Pinning their
output for fixed inputs catches unintended template drift — the exact
"runtime pode alterar artefatos sem evidência" risk called out for root-seed
files — without depending on any local, timestamped, non-tracked file.

To accept an intentional template change, regenerate the fixtures:
    uv run python -c "<see this file's _render_* helpers>" > fixtures/<name>.golden.md
"""

from __future__ import annotations

from pathlib import Path

import pytest

from sdd_wizard.orchestration.seedlings._ai_seed_templates import build_claude_md
from sdd_wizard.orchestration.seedlings._renderer import (
    build_fingerprint_header,
    render_agent_redirector,
)
from sdd_wizard.templates._agents_md_template import build_agents_md

FIXTURES = Path(__file__).parent / "fixtures"

FINGERPRINT = "abc12345"
MANDATE_IDS = ["M001", "M002", "M003"]
GENERATED_AT = "2026-05-22T00:00:00Z"


def _render_claude_md() -> str:
    fp_header = "\n".join(
        build_fingerprint_header(FINGERPRINT, MANDATE_IDS, GENERATED_AT)
    )
    return build_claude_md(fp_header)


def _render_gemini_md() -> str:
    return render_agent_redirector(
        tool_name="Gemini",
        config_paths=[
            ".gemini/commands.md",
            ".gemini/antigravity/skills/",
            "GEMINI.md",
        ],
        fingerprint=FINGERPRINT,
        mandate_ids=MANDATE_IDS,
        generated_at=GENERATED_AT,
    )


def _render_agents_md() -> str:
    return build_agents_md(
        spec_fingerprint=FINGERPRINT,
        generated_at=GENERATED_AT,
        mandate_count=len(MANDATE_IDS),
        ids_preview=", ".join(MANDATE_IDS),
    )


@pytest.mark.parametrize(
    ("render_fn", "golden_name"),
    [
        (_render_claude_md, "claude_md.golden.md"),
        (_render_gemini_md, "gemini_md.golden.md"),
        (_render_agents_md, "agents_md.golden.md"),
    ],
)
def test_root_seed_template_matches_golden(render_fn, golden_name: str) -> None:
    """MUST: root-seed template output is unchanged for fixed inputs (no silent drift)."""
    golden_path = FIXTURES / golden_name
    golden = golden_path.read_text(encoding="utf-8")
    rendered = render_fn()
    assert rendered == golden, (
        f"{golden_name} content drifted for fixed inputs "
        f"(fingerprint={FINGERPRINT!r}, mandate_ids={MANDATE_IDS!r}, "
        f"generated_at={GENERATED_AT!r}).\n"
        "If this is an intentional template change, update the fixture at "
        f"{golden_path}."
    )
