"""IDE-specific governance instruction file generators."""

from pathlib import Path
from typing import Any

from ._shared import (
    _fingerprint_prefix,
    render_agent_redirector,
)

_COPILOT_SDD_ONLY = """# GitHub Copilot Governance Bootstrap

You are operating in a workspace governed by **Spec Driven Development (SDD)**.

## Critical Instruction

Read and adhere to the canonical governance rules in:
```
.sdd/agent-instructions.md
```

This file is the **single source of truth** for all governance policies in this workspace.

## Commands And Skills (Source Of Truth)

1. Commands source of truth: `.sdd/commands`.
2. Skills source of truth: `.sdd/skills`.
3. On startup, load:
   - `.sdd/commands/registry.json`
   - `.sdd/skills/registry.json`
4. For each active command/skill in registries, read canonical files:
   - Commands: `.sdd/commands/<command-id>/command.yaml`
   - Skills: `.sdd/skills/<skill-name>/skill.yaml`
5. Precedence rule:
   - Local path (`.github/prompts/*`) is for context and ergonomics.
   - `.sdd` is authoritative for routing/policy and wins conflicts.

## Quick Reference

- **Mandate enforcement**: Non-negotiable rules (M001-M010, M015)
- **Governance status**: Run `sdd runtime status` to check workspace health
- **Validation**: Run `sdd governance validate` before finalizing changes
- **Activation**: Governance activates automatically on project load via `.sdd/seedlings/`

## Governance Documentation

All governance documentation lives in `.sdd/source/`:
- `mandates/mandates.md` — Mandate descriptions and enforcement rules
- `guidelines/` — Customizable guidelines by category (if any)
- `README.md` — Onboarding guide for agents

## Operating Rules

- Do not bypass mandatory mandates.
- Prefer generated templates and `.sdd/*` canonical governance over improvised structure.
- When the workspace state is unclear, run `sdd runtime status` first.

## Expected Validation Commands

```bash
sdd governance validate
sdd runtime status
```

## Notes

This bootstrap is intentionally a redirector. Do not rely on framework-external paths.

## Safe Fallback

If registries or canonical files are missing/inconsistent, register bootstrap drift and continue in safe fallback mode without inventing missing rules.
"""


def generate_agent_instruction_files(
    output_dir: Path, config: dict[str, Any]
) -> list[tuple[str, Path]]:
    """Generate governance instruction files for supported IDEs and agents."""
    # Safeguard: Never mutate the project root during tests
    import os

    from sdd_core.utils.environment import is_repo_root

    test_output_dir = os.environ.get("SDD_TEST_OUTPUT_DIR")
    if test_output_dir:
        should_block = False
        try:
            # Check if output_dir is a known repo root (has .sdd/ or is a pyproject.toml repo)
            output_resolved = output_dir.resolve()
            if is_repo_root(output_resolved):
                should_block = True
        except (OSError, ValueError):
            # Fallback if resolve fails
            pass

        if should_block:
            msg = f"SDD_ISOLATION_ERROR: Mutation of repo root blocked ({output_dir})"
            print(f"  ❌ {msg}")  # noqa: T201
            raise PermissionError(msg)

    items = config.get("items", [])
    item_count = len(items)

    # G4 Guard: Never generate empty instruction files
    if item_count == 0:
        return []

    core_header = _fingerprint_prefix(config, "core_fingerprint", 16)
    outputs: list[tuple[str, Path, str, list[str]]] = [
        (
            "GitHub Copilot",
            output_dir / ".github" / "copilot-instructions.md",
            "GitHub Copilot",
            [
                "# .github/copilot-instructions.md",
                "# Framework config file",
                "# Generated by: sdd governance generate",
                f"# Governance fingerprint: {core_header}  |  Items: {item_count}",
            ],
        ),
        (
            "VS Code",
            output_dir / ".vscode" / "ai-rules.md",
            "VS Code",
            [
                "# .vscode/ai-rules.md",
                "# Framework config file",
                "# Generated by: sdd governance generate",
            ],
        ),
        (
            "Claude",
            output_dir / ".claude" / "claude-instructions.md",
            "Claude",
            [
                "# .claude/claude-instructions.md",
                "# Framework config file",
                "# Generated by: sdd governance generate",
                f"# Core fingerprint: {core_header}",
            ],
        ),
        (
            "Gemini",
            output_dir / ".gemini" / "gemini-instructions.md",
            "Gemini",
            [
                "# .gemini/gemini-instructions.md",
                "# Framework config file",
                "# Generated by: sdd governance generate",
            ],
        ),
        (
            "Cursor",
            output_dir / ".cursor" / "rules" / "sdd-governance.mdc",
            "Cursor",
            [
                "---",
                "description: SDD governance context — loaded automatically for all files.",
                "globs: ['**/*']",
                "alwaysApply: true",
                "---",
                "# .cursor/rules/sdd-governance.mdc",
                "# Framework config file",
                "# Generated by: sdd governance generate",
            ],
        ),
        (
            "Antigravity",
            output_dir / ".antigravity" / "antigravity-instructions.md",
            "Antigravity",
            [
                "# .antigravity/antigravity-instructions.md",
                "# Framework config file",
                "# Generated by: sdd governance generate",
                f"# Core fingerprint: {core_header}",
            ],
        ),
    ]

    fingerprint = _fingerprint_prefix(config, "core_fingerprint", 16)
    mandate_ids = [
        str(item.get("id", ""))
        for item in config.get("items", [])
        if str(item.get("type", "")).upper() == "MANDATE" and item.get("id")
    ]

    written: list[tuple[str, Path]] = []
    for label, target, tool_name, header_lines in outputs:
        target.parent.mkdir(parents=True, exist_ok=True)
        if label == "GitHub Copilot":
            # Canonical contract: Copilot bootstrap is .sdd-only redirector.
            target.write_text(_COPILOT_SDD_ONLY, encoding="utf-8")
        else:
            target.write_text(
                render_agent_redirector(
                    tool_name, header_lines, fingerprint, mandate_ids
                ),
                encoding="utf-8",
            )
        written.append((label, target))
    return written


def generate_copilot_instructions(output_dir: Path, config: dict[str, Any]) -> Path:
    """Generate .github/copilot-instructions.md with real governance content.

    Derives content from governance-core.json items: MANDATEs, GUIDELINEs,
    and DECISION items with their descriptions.

    Args:
        output_dir: Workspace root (file goes to output_dir/.github/).
        config: Governance config dict loaded from governance-core.json.

    Returns:
        Path to the written copilot-instructions.md file.
    """
    return generate_agent_instruction_files(output_dir, config)[0][1]
