"""Agent seed generators — standalone MD context files per AI platform."""

from pathlib import Path
from typing import Any

from ._shared import _fingerprint_prefix, _format_rules, _render_instruction_document


def _generate_cursor_seed(
    config: dict[str, Any],
    mandatory_rules: list[dict[str, Any]],
    customizable_items: list[dict[str, Any]],
) -> str:
    """Generate Cursor IDE specific agent seed."""
    core_fp = _fingerprint_prefix(config, "core_fingerprint")
    return f"""# Cursor Agent Configuration

## Governance Context
- **Core Fingerprint**: {core_fp}
- **Status**: Production Ready
- **Total Items**: {len(config.get("items", []))}

## Mandatory Governance Rules
These rules must be enforced in every implementation:

{_format_rules(mandatory_rules)}

## Governance Checklist
Before implementing any feature:
- [ ] Validate against mandatory rules
- [ ] Check for conflicts with existing items
- [ ] Ensure customizable items are respected
- [ ] Verify fingerprints match core specification

## Customizable Items
Your project can customize {len(customizable_items)} governance items.

See `.sdd/source/` for complete specification.

## Integration Points
- Bootstrap status: `sdd runtime status`
- Validate changes: `sdd governance validate`
- Generate templates: `sdd governance generate`
- Query context: `sdd ask-full "<question>"`
"""


def _generate_copilot_seed(
    config: dict[str, Any],
    mandatory_rules: list[dict[str, Any]],
    customizable_items: list[dict[str, Any]],
) -> str:
    """Generate GitHub Copilot agent seed."""
    core_fp = _fingerprint_prefix(config, "core_fingerprint")
    client_fp = _fingerprint_prefix(config, "client_fingerprint")
    return f"""# GitHub Copilot Governance Context

## Architecture Context
This codebase follows SDD (Spec Driven Development) with compiled governance enforcement.

- **Core Fingerprint**: {core_fp}
- **Client Fingerprint**: {client_fp}
- **Items Protected**: 4 core immutable + {len(customizable_items)} customizable

## Critical Rules (Immutable)

{_format_rules(mandatory_rules)}

## Before Suggesting Code
1. Check mandatory rules above
2. Respect customizable governance items
3. Validate against `.sdd/compiled/` specifications
4. Use compiled artifacts via: `sdd ask-full "<question>"`

## Key Resources
- Compiled governance: `.sdd/compiled/audit/metadata-core.json`
- Specifications: `.sdd/source/`

## Governance Validation
Run `sdd governance validate` to ensure compliance before commits.
"""


def _generate_generic_seed(
    config: dict[str, Any],
    mandatory_rules: list[dict[str, Any]],
    customizable_items: list[dict[str, Any]],
) -> str:
    """Generate generic AI agent seed."""
    return f"""# AI Agent Governance Configuration

## Specification Summary
- **Architecture**: SDD (Spec Driven Development)
- **Governance Model**: Compiled artifacts in `.sdd/compiled/`
- **Total Managed Items**: {len(config.get("items", []))}
- **Enforcement Level**: Strict (fingerprint-based verification)

## Governance Fingerprints
```
Core Fingerprint:   {config.get("core_fingerprint", "N/A")}
Client Fingerprint: {config.get("client_fingerprint", "N/A")}
```

## Mandatory Rules

{_format_rules(mandatory_rules)}

## Implementation Guidelines

### When Implementing Features:
1. Load governance context via: `sdd ask-full "<question>"`
2. Check mandatory rules (immutable)
3. Respect customizable items (can be extended)
4. Validate before commit: `sdd governance validate`

### Key Commands:
```bash
sdd runtime status          # Bootstrap status
sdd governance validate     # Validate integrity
sdd governance generate     # Generate artifacts
sdd governance compile      # Recompile from source
```

## Directory Structure
```
Framework:
    |-- .sdd/                 # Compiled governance artifacts
    |   |-- compiled/         # .msgpack + metadata JSON
    |   `-- source/           # Human-readable source
    `-- packages/             # Core infrastructure
```
"""


def _generate_claude_seed(
    config: dict[str, Any],
    mandatory_rules: list[dict[str, Any]],
    customizable_items: list[dict[str, Any]],
) -> str:
    """Generate Claude-specific agent seed with full bootstrap guidance."""
    core_fp = _fingerprint_prefix(config, "core_fingerprint", 16)
    return _render_instruction_document(
        tool_name="Claude",
        header_lines=[
            "# claude-agent.md",
            f"# Claude Agent Seed — Core fingerprint: {core_fp}",
            "# Generated by: sdd governance generate",
            f"# Customizable items: {len(customizable_items)}",
        ],
        config=config,
    )


def _generate_gemini_seed(
    config: dict[str, Any],
    mandatory_rules: list[dict[str, Any]],
    customizable_items: list[dict[str, Any]],
) -> str:
    """Generate Gemini-specific agent seed."""
    client_fp = _fingerprint_prefix(config, "client_fingerprint")
    return f"""# Gemini Governance Context

## Workspace Snapshot
- **Client Fingerprint**: {client_fp}
- **Managed Items**: {len(config.get("items", []))}
- **Customizable Items**: {len(customizable_items)}

## Immutable Rules

{_format_rules(mandatory_rules)}

## Working Protocol
1. Confirm active governance items before code suggestions
2. Preserve architectural decisions and mandatory rules
3. Query compiled artifacts: `sdd ask-full "<question>"`
4. Validate with `sdd governance validate` before completion
"""


def _generate_cortex_seed(
    config: dict[str, Any],
    mandatory_rules: list[dict[str, Any]],
    customizable_items: list[dict[str, Any]],
) -> str:
    """Generate Snowflake Cortex Code agent seed."""
    core_fp = _fingerprint_prefix(config, "core_fingerprint")
    return f"""# Cortex Code Agent Configuration

## Governance Context
- **Core Fingerprint**: {core_fp}
- **Status**: Production Ready
- **Total Items**: {len(config.get("items", []))}

## Mandatory Governance Rules
These rules must be enforced in every implementation:

{_format_rules(mandatory_rules)}

## Governance Checklist
Before implementing any feature:
- [ ] Validate against mandatory rules
- [ ] Check for conflicts with existing items
- [ ] Ensure customizable items are respected
- [ ] Verify fingerprints match core specification

## Customizable Items
Your project can customize {len(customizable_items)} governance items.

See `.sdd/source/` for complete specification.

## Integration Points
- Bootstrap status: `sdd runtime status`
- Validate changes: `sdd governance validate`
- Generate templates: `sdd governance generate`
- Query context: `sdd ask-full "<question>"`
"""


def _generate_antigravity_seed(
    config: dict[str, Any],
    mandatory_rules: list[dict[str, Any]],
    customizable_items: list[dict[str, Any]],
) -> str:
    """Generate Antigravity-specific agent seed."""
    core_fp = _fingerprint_prefix(config, "core_fingerprint")
    client_fp = _fingerprint_prefix(config, "client_fingerprint")
    return f"""# Antigravity Governance Context

## Governance Envelope
- **Core Fingerprint**: {core_fp}
- **Client Fingerprint**: {client_fp}
- **Managed Items**: {len(config.get("items", []))}
- **Customizable Items**: {len(customizable_items)}

## Mandatory Rules

{_format_rules(mandatory_rules)}

## Enforcement Notes
1. Treat governance mandates as non-negotiable
2. Use compiled artifacts as source of truth: `.sdd/compiled/`
3. Query context: `sdd ask-full "<question>"`
4. Run `sdd governance validate` and `sdd runtime status` before handoff
"""


def generate_agent_seeds(
    output_dir: Path, config: dict[str, Any]
) -> list[tuple[str, Path, str]]:
    """Generate agent seed templates for different AI platforms.

    Args:
        output_dir: Directory to save agent seeds
        config: Governance configuration dictionary

    Returns:
        List of tuples: (agent_name, file_path, status)
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    items = config.get("items", [])
    mandatory_rules = [
        i
        for i in items
        if str(i.get("type", "")).upper() == "MANDATE"
        or (i.get("type") == "rule" and i.get("is_immutable"))
    ]
    customizable_items = [i for i in items if not i.get("is_immutable")]

    seeds = [
        ("Cursor IDE", "cursor-agent.md", _generate_cursor_seed),
        ("GitHub Copilot", "copilot-agent.md", _generate_copilot_seed),
        ("Generic AI", "generic-agent.md", _generate_generic_seed),
        ("Claude", "claude-agent.md", _generate_claude_seed),
        ("Gemini", "gemini-agent.md", _generate_gemini_seed),
        ("Antigravity", "antigravity-agent.md", _generate_antigravity_seed),
        ("Cortex Code", "cortex-agent.md", _generate_cortex_seed),
    ]

    results: list[tuple[str, Path, str]] = []
    for label, filename, generator in seeds:
        path = output_dir / filename
        path.write_text(
            generator(config, mandatory_rules, customizable_items), encoding="utf-8"
        )
        results.append((label, path, "Generated"))

    return results
