"""Claude-specific bootstrap section renderer for AI agent instruction documents."""

from __future__ import annotations


def _render_claude_bootstrap_sections() -> list[str]:
    """Return Claude-specific bootstrap, quiz, and navigation sections."""
    return [
        "## Agent Entrypoint (Bootstrap)",
        "",
        "Every Claude session MUST follow this sequence:",
        "",
        "1. DISCOVERY     → Check `.sdd/profile` (governance exists?)",
        "2. HANDSHAKE     → Load indices, activate governance",
        "3. LOAD CORE     → mandates/index, policies/index, rules/index",
        "4. VERIFICATION  → Context Verification quiz (2 questions)",
        "5. TASK CLASS    → Classify work (PATH A/B/C/D)",
        "6. CONTEXT LOAD  → Load minimal context (strategy + budget)",
        "7. DECISION      → CONTEXT_SELECTION + EXECUTION_DECISION",
        "8. ANTI-PATTERN  → Validate no violations",
        "9. EXECUTE       → Mandates > Policies > Rules",
        "10. VALIDATE     → Compliance check",
        "11. OUTPUT       → [SDD STATUS] Governance: ACTIVE",
        "",
        "**Reference:** `.sdd/source/README.md`",
        "",
        "## Pre-Execution: The Two-Question Quiz",
        "",
        "BEFORE any research or action, ask:",
        "",
        "1. Do Governance Rules (`.sdd/source/`) already solve this?",
        "   - If YES → Apply and return. Don't proceed.",
        "   - If NO → Next question.",
        "",
        "2. Does the Local Cache (`.sdd/runtime/.sdd-cache.md`) already solve this?",
        "   - If YES → Use cached info and return.",
        "   - If NO → Only then expand context or research.",
        "",
        "**Reference:** `.sdd/source/README.md`",
        "",
        "## Optimized Context Loading from .sdd/",
        "",
        "Load context in this order (minimal to complete):",
        "",
        "**Level 1 (MUST HAVE):**",
        "- `.sdd/metadata.json` — Version, fingerprints, item counts",
        "- `.sdd/compiled/audit/metadata-core.json` — Core governance state",
        "- `CLAUDE.md` — This file (bootstrap sequence)",
        "",
        "**Level 2 (AS NEEDED):**",
        "- `.sdd/source/mandates/mandates.md` — Full mandate descriptions",
        "- `.sdd/source/README.md` — Pre-cache strategy",
        "",
        "**Level 3 (IF SPECIFIC):**",
        "- `.sdd/source/guidelines/guidelines.md`",
        "- `.sdd/source/mandates/mandates.md`",
        "- `.sdd/compiled/audit/metadata-client-template.json`",
        "",
        "**Agent Memory:** Store loaded context in `.claude/projects/*/memory/`",
        "- Avoids re-reading same artifacts",
        "- Helps subagents bootstrap faster",
        "",
        "## Git & Commit Protocol (P003 Enforcement)",
        "",
        'Golden Rule: "Agents propose, Humans dispose"',
        "",
        "1. Agent SUGGESTS complete command (code block)",
        "2. Agent NEVER executes git operations autonomously",
        "3. Human reviews diff + commit message",
        "4. Human executes or explicitly approves",
        "",
        "**Reference:** `.sdd/source/mandates/mandates.md`",
        "",
    ]
