"""Pure helpers for reading and checking governance configuration."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from sdd_core.utils.managed_block import extract_managed_block

_ROOT_SEED_FILES = ("AGENTS.md", "CLAUDE.md", "GEMINI.md")
_FINGERPRINT_HEADER_RE = re.compile(r"Governance fingerprint:\s*([0-9a-fA-F]+)")


def _workspace_root_from_governance_path(path: str) -> Path:
    """Best-effort workspace root resolution from a governance path."""
    resolved = Path(path).resolve()
    if resolved.name == "compiled" and resolved.parent.name == ".sdd":
        return resolved.parent.parent
    if resolved.name == ".sdd":
        return resolved.parent
    return resolved.parent


def check_files_accessible(path: str) -> bool:
    """Check if all required governance files are accessible."""
    from sdd_cli.utils.loader import validate_governance_path

    return validate_governance_path(path)


def check_fingerprints_valid(config: dict[str, Any] | None) -> bool:
    """Check if governance fingerprints are valid."""
    try:
        if config is None:
            return False
        return (
            config.get("core_fingerprint") is not None
            and config.get("client_fingerprint") is not None
        )
    except Exception:
        return False


def check_no_conflicts(config: dict[str, Any] | None) -> bool:
    """Check for conflicts in governance configuration."""
    try:
        if config is None:
            return False
        return config.get("core_fingerprint") != config.get("client_fingerprint")
    except Exception:
        return False


def _classify_seed_file(
    seed_file: Path,
    filename: str,
    expected_fingerprint: str,
    drifted: list[str],
    unmanaged: list[str],
) -> None:
    """Classify one root seed file into `drifted`/`unmanaged` (mutated in place).

    Split out of `check_root_seed_drift` to keep both functions under the
    project's cyclomatic-complexity threshold.
    """
    if not seed_file.exists():
        return
    try:
        content = seed_file.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return
    block_body = extract_managed_block(content)
    if block_body is None:
        unmanaged.append(filename)
        return
    match = _FINGERPRINT_HEADER_RE.search(block_body)
    if match and match.group(1) != expected_fingerprint:
        drifted.append(filename)


def check_root_seed_drift(path: str) -> tuple[bool, str]:
    """Compare the fingerprint header inside root seed files' managed block
    against metadata.json.

    Root seed files (AGENTS.md, CLAUDE.md, GEMINI.md) are shared-namespace
    filenames — conventions other AI tools/agents independently recognize —
    so sdd only ever reads, writes, or validates its own delimited
    `<!-- sdd:managed:begin/end -->` region inside them, never the whole
    file (see
    `.analysis/refined/20260906-root-seed-githook-necessity/design.md`).
    A file with no managed block (never generated by this workspace's
    tooling, or predating this convention) is `unmanaged` — sdd has nothing
    to say about content it never claimed, so this never fails the check.
    Only a managed block that is present and stale counts as drift,
    regardless of the file's git-tracked status — tracked/untracked was
    explored and rejected as the enforcement axis (see design.md's
    "Revision 1" note); ownership of the *content*, not git history, is
    what makes a fingerprint mismatch meaningful.

    Independent of `sdd ask`'s in-session `check_fingerprint_drift` (which
    compares cached runtime state, not installed root files against source
    metadata).
    """
    workspace_root = _workspace_root_from_governance_path(path)
    metadata_file = workspace_root / ".sdd" / "metadata.json"
    if not metadata_file.exists():
        return True, "metadata.json not found — skipping root-seed drift check"

    try:
        metadata = json.loads(metadata_file.read_text(encoding="utf-8"))
    except Exception:
        return True, "metadata.json unreadable — skipping root-seed drift check"

    expected_fingerprint = metadata.get("governance_fingerprint") or metadata.get(
        "fingerprints", {}
    ).get("combined")
    if not expected_fingerprint:
        return (
            True,
            "no governance_fingerprint in metadata.json — skipping root-seed drift check",
        )

    drifted: list[str] = []
    unmanaged: list[str] = []
    for filename in _ROOT_SEED_FILES:
        _classify_seed_file(
            workspace_root / filename,
            filename,
            expected_fingerprint,
            drifted,
            unmanaged,
        )

    if drifted:
        return (
            False,
            f"root-seed fingerprint drift in managed block of: {', '.join(drifted)}",
        )
    if unmanaged:
        return (
            True,
            "no root-seed drift detected (no managed block found in: "
            f"{', '.join(unmanaged)} — not sdd's content, not validated; "
            "run your workspace's onboarding bootstrap to add one)",
        )
    return True, "no root-seed drift detected"
