"""OTel attribute key names used when building event attribute dicts."""

SERVICE_NAME_KEY = "service.name"
SERVICE_VERSION_KEY = "service.version"
EVENT_NAME_KEY = "event.name"
EVENT_DOMAIN_KEY = "event.domain"
EVENT_DOMAIN_VALUE = "sdd.governance"
EVENT_TIME_KEY = "event.time"
LOG_SEVERITY_KEY = "log.severity"
LOG_SEVERITY_NUMBER_KEY = "log.severity_number"
SDD_EVENT_TYPE_KEY = "sdd.event.type"
SDD_EVENT_TIMESTAMP_KEY = "sdd.event.timestamp"
TRACE_ID_KEY = "sdd.trace_id"
SPAN_ID_KEY = "sdd.span_id"
