"""Canonical markdown template for .providence/agent-instructions.md.

Used by both the initial wizard seedling path (`initial_seedling=True`) and
the governance-seeds regeneration path (`initial_seedling=False`, default).
The two paths previously had independently-drifted content (see SQ-004); this
merges them into one source, keeping the fuller content (Enforcement Scope
section, closing golden-rule note) that only the initial-seedling path had.
"""

from __future__ import annotations

from providence_wizard.templates._hard_mode_rules import HARD_MODE_RULES_SECTION


def build_agent_instructions_content(
    fingerprint: str,
    generated_at: str,
    mandate_count: int,
    ids_preview: str,
    mandates_list: str,
    *,
    initial_seedling: bool = False,
) -> str:
    """Return the full .providence/agent-instructions.md content."""
    header_verb = (
        "Generated by: providence wizard"
        if initial_seedling
        else "Regenerated by: providence governance generate"
    )
    generated_label = "Generated at" if initial_seedling else "Regenerated at"
    header = f"""# SDD Agent Instructions  Authority & Bootstrap
# {header_verb}
# Governance fingerprint: {fingerprint}
# Active mandates: {mandate_count}{" (" + ids_preview + ")" if ids_preview else ""}
# {generated_label}: {generated_at}

**This workspace is governed by Spec Driven Development (SDD).**

You MUST NOT proceed without reading this file in its entirety."""

    return f"""{header}

---

## 1. Authority Hierarchy

**The source of truth for all governance is this directory (`.providence/`).**

```
.providence/
 metadata.json                       Workspace version + fingerprints
 agent-instructions.md               THIS FILE (you are reading it)
 compiled/                           Optional binary/runtime artifacts (may be absent in template handoff)
 source/
     mandates/mandates.md            Mandate descriptions (enforcement rules)
     README.md
```

**Do not trust CLAUDE.md, .vscode/, .cursor/, or any other "convenience" pointers over what is in `.providence/`.**

---

## 2. Mandatory Bootstrap (3 steps)

Before planning, coding, or deciding:

1. **Read `.providence/metadata.json`**
   - Check `version` (currently 3.0)
   - Check `mandates_count` (count of active mandates)
   - Verify workspace is not stale
   - Expected fingerprint prefix (first 8 chars): {fingerprint}

2. **Read `.providence/metadata.json`**
   - Extract mandate IDs and titles
   - Example: `"items": [{{"id": "M001", "title": "Clean Architecture"}}, ...]`
   - If `items` is empty or count < 4, governance is broken  escalate to human

3. **Read `.providence/source/mandates/mandates.md`**
   - Understand enforcement rules for each active mandate
   - If descriptions are stale or missing, request governance regeneration from the human

---

## 3. Active Mandates (read from `.providence/source/`)

The authoritative human-readable list is in `.providence/metadata.json`, not this file.

**Current snapshot** (validate this against `.providence/metadata.json`):
{mandates_list}

---

## 4. Pre-Task Checklist

Before starting any work:

- [ ] `.providence/metadata.json` read  version, fingerprint, count verified
- [ ] `.providence/metadata.json` read  mandates extracted
- [ ] `.providence/source/mandates/mandates.md` read  enforcement rules understood
- [ ] No contradictions between this file and `.providence/` (if found  escalate)

**If you cannot complete this checklist, do not proceed  ask the human first.**

---

## 5. Enforcement Scope

Mandates (HARD) are non-negotiable and always take precedence.

Policies, rules, and guidelines (SOFT) must also be applied when they do not conflict with mandates.

Git protocol (M010), testing, architecture, and token budgets must be followed.

### HARD Constraints  Never Violate

These constraints are non-negotiable. Violation requires human escalation, not auto-correction.

- **M010 (Delivery Hygiene)**: NEVER execute git state-modifying commands (add, commit, push, reset, merge, rebase, branch -D, etc.) autonomously via any tool or shell. ONLY suggest git commands in ready-to-run blocks for human execution.
  - Corollary: Task completion does NOT authorize a commit. Only explicit user request does.
  - Read: `.providence/source/mandates/mandates.md#M010`

---

{HARD_MODE_RULES_SECTION}

---

## 6. Fallback & Escalation

**If `.providence/` is incomplete or inconsistent:**
- **STOP EXECUTION IMMEDIATELY. Do not guess or interpolate.**
- Escalate to human: "`.providence/` is broken: [specific problem]"
- Example: "`.providence/metadata.json` has only 1 mandate but `.providence/metadata.json` claims 4"
- You must refuse to bypass the governance gate.

**This is not a blocker  it's a signal that the human should regenerate the workspace.**

---

## 7. Fingerprint Integrity Check

**Fingerprint this version:** `{fingerprint}`
**{generated_label}:** {generated_at}

Before starting any task, verify bootstrap integrity:

1. Read the fingerprint in your bootstrap file header (e.g. `# Governance fingerprint:` in CLAUDE.md)
2. Compare with `.providence/metadata.json`  field `governance_fingerprint`
3. If they differ, governance was updated after bootstrap. Run `providence governance generate` to sync.

If `providence governance generate` does not update `.providence/agent-instructions.md`, ask the human to run `providence wizard` again.

**Golden rule:** Fingerprint in bootstrap file = fingerprint in metadata.json. Divergence = drift.

---

## 8. M015 Handshake  Required Before First Action

Before taking any governed action in this workspace, complete the
bidirectional agent handshake yourself (this is a genuine attestation, not a
formality  do not skip it or mechanically copy-paste without reading the
files above first):

1. `providence governance handshake --init`
   Generates a challenge JSON (session_id, active_mandates, available_skills).

2. `providence governance handshake --response '<json>'`
   Submit a response after actually reading this file and `.providence/metadata.json`:
   ```json
   {{
     "agent_id": "<your agent identity>",
     "understood_mandates": [<active mandate IDs from step 1>],
     "skills_to_use": [<skills you intend to invoke>],
     "acknowledged_signature": true,
     "compliance_declaration": true
   }}
   ```

Without this, `providence governance validate` reports `Active handshake (M015):
FAIL`. The response has no expiry once submitted  do it once per new agent
session, not on every command.
"""
