"""Shared redirector renderer for all AI agent bootstrap files.

Produces lightweight governance redirectors with fingerprint headers.
Mirror in providence_cli/generators/_shared.py  keep output format in sync.
"""

from __future__ import annotations

def build_fingerprint_header(
    fingerprint: str,
    mandate_ids: list[str],
    generated_at: str,
) -> list[str]:
    """Return comment lines for the top of any agent bootstrap file."""
    ids_preview = ", ".join(mandate_ids[:5])
    if len(mandate_ids) > 5:
        ids_preview += ", ..."
    return [
        f"# Governance fingerprint: {fingerprint[:16]}",
        f"# Active mandates: {len(mandate_ids)}"
        + (f" ({ids_preview})" if ids_preview else ""),
        f"# Generated: {generated_at}",
        "# Drift check: fingerprint must match .providence/metadata.json  fingerprints.combined",
    ]


def render_agent_redirector(
    tool_name: str,
    config_paths: list[str],
    fingerprint: str,
    mandate_ids: list[str],
    generated_at: str,
) -> str:
    """Render a lightweight governance redirector for an AI agent bootstrap file.

    All agent bootstrap files follow this contract:
    - fingerprint header (drift detection)
    - redirect to .providence/agent-instructions.md as single source of truth
    - no inline mandate descriptions
    """
    header = build_fingerprint_header(fingerprint, mandate_ids, generated_at)
    header_block = "\n".join(header)

    paths_block = "\n".join(f"   - `{p}`" for p in config_paths)

    return f"""# {tool_name}  SDD Governance Bootstrap
# Generated by: providence wizard
{header_block}

You are operating in a workspace governed by **Spec Driven Development (SDD)**.

## Entrypoint Contract

1. You must learn commands and skills from your custom folder path:
{paths_block}
2. You are under governance. Always resolve instructions from `.providence`.
   Initial reference:
   - `.providence/agent-instructions.md`

## Commands And Skills (Source Of Truth)

1. Commands source of truth: `.providence/commands`.
2. Skills source of truth: `.providence/skills`.
3. On startup, load:
   - `.providence/commands/registry.json`
   - `.providence/skills/registry.json`
4. For each active command/skill in registries, read canonical files:
   - Commands: `.providence/commands/<command-id>/command.yaml`
   - Skills: `.providence/skills/<skill-name>/skill.yaml`
5. Precedence rule:
   - Local path is for context and ergonomics.
   - `.providence` is authoritative for routing/policy and wins conflicts.

## One Rule

**Before planning, coding, or deciding:** read `.providence/agent-instructions.md`.

If that file says something different from what you remember seeing in this file,
**trust `.providence/agent-instructions.md`  it is authoritative.**

## Quick Reference

| File | Purpose |
|------|---------|
| `.providence/agent-instructions.md` | **START HERE**  Complete agent bootstrap |
| `.providence/metadata.json` | Workspace version, fingerprints, item counts |
| `.providence/metadata.json` | Human-readable mandates snapshot |
| `.providence/source/mandates/mandates.md` | Full mandate descriptions |

## Safe Fallback

If registries or canonical files are missing/inconsistent, register bootstrap drift
and continue in safe fallback mode without inventing missing rules.
"""
