"""Shared constants and reason codes for skill execution."""

from __future__ import annotations

from collections.abc import Callable

__all__ = [
    "MIN_DIAGNOSIS_CONFIDENCE_DEFAULT",
    "ATTESTATION_TTL_MINUTES_DEFAULT",
    "CONVERGENCE_FREEZE_ALIGNMENT_THRESHOLD",
    "REASON_CODE_CONTRACT_MISSING_OR_INVALID",
    "REASON_CODE_DIAGNOSIS_MISSING",
    "REASON_CODE_DIAGNOSIS_INCONCLUSIVE",
    "REASON_CODE_DIAGNOSIS_STALE",
    "REASON_CODE_SCOPE_VIOLATION",
    "REASON_CODE_EVIDENCE_INSUFFICIENT",
    "REASON_CODE_RULE_BLOCKED",
    "REASON_CODE_CONVERGENCE_FREEZE",
    "REASON_CODE_GATE_RULES_INVALID",
    "_FooterFn",
]

MIN_DIAGNOSIS_CONFIDENCE_DEFAULT = 0.80
ATTESTATION_TTL_MINUTES_DEFAULT = 30
CONVERGENCE_FREEZE_ALIGNMENT_THRESHOLD = 0.60
REASON_CODE_CONTRACT_MISSING_OR_INVALID = "contract.missing_or_invalid"
REASON_CODE_DIAGNOSIS_MISSING = "diagnosis.missing"
REASON_CODE_DIAGNOSIS_INCONCLUSIVE = "diagnosis.inconclusive"
REASON_CODE_DIAGNOSIS_STALE = "diagnosis.stale"
REASON_CODE_SCOPE_VIOLATION = "scope.violation"
REASON_CODE_EVIDENCE_INSUFFICIENT = "evidence.insufficient"
REASON_CODE_RULE_BLOCKED = "rule.blocked"
REASON_CODE_CONVERGENCE_FREEZE = "convergence.freeze_mode_active"
REASON_CODE_GATE_RULES_INVALID = "gate.rules.invalid"

_FooterFn = Callable[[str, str], str]
