"""Patterns for scalar type fields: booleans, HTTP status/method, log level, env, and more."""

from sdd_telemetry.types import PatternDef

TYPE_PATTERNS: dict[str, PatternDef] = {
    "TYPE001": {
        "name": "Boolean True",
        "values": [True, "true", "TRUE", "yes", "YES", "1"],
        "fields": ["active", "enabled", "is_active", "success"],
        "compression_ratio": 0.08,
        "frequency": 0.50,
    },
    "TYPE002": {
        "name": "Boolean False",
        "values": [False, "false", "FALSE", "no", "NO", "0"],
        "fields": ["active", "enabled", "is_active", "success"],
        "compression_ratio": 0.08,
        "frequency": 0.50,
    },
    "TYPE003": {
        "name": "Null/None Value",
        "values": [None, "null", "NULL", "nil"],
        "fields": ["value", "result", "data"],
        "compression_ratio": 0.05,
        "frequency": 0.30,
    },
    "TYPE004": {
        "name": "HTTP Status Code",
        "values": [
            200,
            201,
            204,
            301,
            302,
            304,
            400,
            401,
            403,
            404,
            405,
            500,
            502,
            503,
        ],
        "fields": ["status", "http_status", "code"],
        "compression_ratio": 0.06,
        "frequency": 0.85,
    },
    "TYPE005": {
        "name": "Log Level",
        "values": ["DEBUG", "INFO", "WARN", "WARNING", "ERROR", "FATAL", "CRITICAL"],
        "fields": ["level", "log_level", "severity"],
        "compression_ratio": 0.10,
        "frequency": 0.90,
    },
    "TYPE006": {
        "name": "HTTP Method",
        "values": ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS", "HEAD"],
        "fields": ["method", "http_method"],
        "compression_ratio": 0.07,
        "frequency": 0.80,
    },
    "TYPE007": {
        "name": "Content Type",
        "values": [
            "application/json",
            "text/html",
            "text/plain",
            "application/xml",
            "image/png",
        ],
        "fields": ["content_type", "media_type"],
        "compression_ratio": 0.25,
        "frequency": 0.70,
    },
    "TYPE008": {
        "name": "Environment",
        "values": ["development", "staging", "production", "test", "local"],
        "fields": ["environment", "env", "stage"],
        "compression_ratio": 0.08,
        "frequency": 0.95,
    },
    "TYPE009": {
        "name": "Percentage",
        "regex": r"^(100|[0-9]{1,2})(\.[0-9]+)?%?$",
        "fields": ["percentage", "percent", "progress"],
        "compression_ratio": 0.12,
        "frequency": 0.35,
    },
    "TYPE010": {
        "name": "Byte Size (B/KB/MB/GB)",
        "regex": r"^\d+(\.\d+)?\s?(B|KB|MB|GB|TB)$",
        "fields": ["size", "file_size", "memory"],
        "compression_ratio": 0.15,
        "frequency": 0.40,
    },
    "TYPE011": {
        "name": "Language Code",
        "regex": r"^[a-z]{2}(-[A-Z]{2})?$",
        "fields": ["language", "lang", "locale"],
        "compression_ratio": 0.08,
        "frequency": 0.25,
    },
    "TYPE012": {
        "name": "Currency Code",
        "regex": r"^[A-Z]{3}$",
        "fields": ["currency", "iso_code"],
        "compression_ratio": 0.06,
        "frequency": 0.20,
    },
}
