"""Tests for generated IDE instruction files contracts."""

from pathlib import Path

from sdd_cli.generators._instruction_files import generate_agent_instruction_files

FINGERPRINT = "21b6f7d81c88d0c0"
MANDATE_DESC = (
    "Clean Architecture mandate long inline description that should not appear"
)


def _sample_config() -> dict:
    return {
        "core_fingerprint": FINGERPRINT,
        "client_fingerprint": "792a262a16f8e344",
        "items": [
            {
                "id": "M001",
                "type": "MANDATE",
                "title": "Clean Architecture",
                "description": MANDATE_DESC,
            },
            {"id": "G001", "type": "GUIDELINE", "title": "Style"},
        ],
    }


def test_copilot_instructions_use_sdd_only_redirector(tmp_path: Path) -> None:
    """Copilot instructions must be authority redirector, not framework-path bootstrap."""
    generate_agent_instruction_files(tmp_path, _sample_config())
    content = (tmp_path / ".github" / "copilot-instructions.md").read_text(
        encoding="utf-8"
    )
    assert ".sdd/agent-instructions.md" in content
    assert "sdd runtime status" in content
    assert "sdd governance validate" in content
    assert ".sdd/commands/registry.json" in content
    assert ".sdd/skills/registry.json" in content
    assert ".sdd/commands/<command-id>/command.yaml" in content
    assert ".sdd/skills/<skill-name>/skill.yaml" in content
    assert ".spec.config" not in content
    assert ".../EXECUTION/" not in content


# ---------------------------------------------------------------------------
# Static template format regression: no .spec.config legacy references
# ---------------------------------------------------------------------------


def _sdd_integration_template(rel: str) -> Path:
    import sdd_integration

    return Path(sdd_integration.__file__).parent / "templates" / rel


def test_static_claude_instructions_no_spec_config() -> None:
    f = _sdd_integration_template(".claude/claude-instructions.md")
    if not f.exists():
        return
    content = f.read_text(encoding="utf-8")
    assert ".spec.config" not in content, (
        "claude-instructions.md still references legacy .spec.config"
    )
    assert ".sdd/agent-instructions.md" in content


def test_static_gemini_instructions_no_spec_config() -> None:
    f = _sdd_integration_template(".gemini/gemini-instructions.md")
    if not f.exists():
        return
    content = f.read_text(encoding="utf-8")
    assert ".spec.config" not in content, (
        "gemini-instructions.md still references legacy .spec.config"
    )
    assert ".sdd/agent-instructions.md" in content


def test_static_antigravity_instructions_no_spec_config() -> None:
    f = _sdd_integration_template(".antigravity/antigravity-instructions.md")
    if not f.exists():
        return
    content = f.read_text(encoding="utf-8")
    assert ".spec.config" not in content, (
        "antigravity-instructions.md still references legacy .spec.config"
    )
    assert ".sdd/agent-instructions.md" in content


# ---------------------------------------------------------------------------
# Antigravity regenerated by sdd governance generate
# ---------------------------------------------------------------------------


def test_antigravity_regenerated_by_governance_generate(tmp_path: Path) -> None:
    """sdd governance generate must produce antigravity instructions."""
    generate_agent_instruction_files(tmp_path, _sample_config())
    antigravity_file = tmp_path / ".antigravity" / "antigravity-instructions.md"
    assert antigravity_file.exists(), (
        ".antigravity/antigravity-instructions.md not generated"
    )
    content = antigravity_file.read_text(encoding="utf-8")
    assert ".sdd/agent-instructions.md" in content
    assert FINGERPRINT in content


def test_antigravity_no_inline_mandate_descriptions(tmp_path: Path) -> None:
    generate_agent_instruction_files(tmp_path, _sample_config())
    content = (tmp_path / ".antigravity" / "antigravity-instructions.md").read_text(
        encoding="utf-8"
    )
    assert MANDATE_DESC not in content


# ---------------------------------------------------------------------------
# VSCode/Cursor: no inline mandate descriptions after sdd governance generate
# ---------------------------------------------------------------------------


def test_vscode_no_inline_mandate_descriptions(tmp_path: Path) -> None:
    generate_agent_instruction_files(tmp_path, _sample_config())
    content = (tmp_path / ".vscode" / "ai-rules.md").read_text(encoding="utf-8")
    assert MANDATE_DESC not in content
    assert ".sdd/agent-instructions.md" in content
    assert FINGERPRINT in content


def test_cursor_no_inline_mandate_descriptions(tmp_path: Path) -> None:
    generate_agent_instruction_files(tmp_path, _sample_config())
    content = (tmp_path / ".cursor" / "rules" / "sdd-governance.mdc").read_text(
        encoding="utf-8"
    )
    assert MANDATE_DESC not in content
    assert ".sdd/agent-instructions.md" in content
    assert FINGERPRINT in content
