"""Template builders for .sdd/source/README.md and .sdd/runtime/README.md."""

from __future__ import annotations


def build_source_readme(
    generated_at: str,
    language: str,
    adoption_level: str,
    guideline_category_block: str,
    guideline_read_examples: str,
    language_context_lines: str,
    categories_list: str,
    mandate_count: int,
    guideline_count: int,
) -> str:
    """Return the full .sdd/source/README.md content."""
    return f"""# .sdd/source - Governance Source of Truth

⚡ **For AI Agents: This is your primary query directory**

## Overview

This directory contains the **compiled and optimized** governance specifications that agents should reference.

**Generated**: {generated_at}
**Language**: {language}
**Adoption Level**: {adoption_level}

## Directory Structure

```
.sdd/source/
├── mandates/
│   └── mandates.md              ← Read mandates first (hard rules)
├── guidelines.dsl               ← Guideline source of truth (universal + tagged)
├── guidelines/
{guideline_category_block}└── README.md                    ← This file
```

## For AI Agents: How to Use This

### 1. Query Mandates First

Always read `.sdd/source/mandates/mandates.md` to understand **hard rules** that CANNOT be customized.

```
cat .sdd/source/mandates/mandates.md
```

### 2. Query Relevant Guidelines

Based on the task, read relevant guidelines:

```
# Full DSL source
cat .sdd/source/guidelines.dsl

# Example rendered category files
{guideline_read_examples}```

### 3. Use As Pre-Cache Context

These files are **optimized for AI parsing** (IA-FIRST format):
- Flat hierarchy (H2 sections, no skipped levels)
- Clear lists instead of prose
- Emoji markers for decisions
- Markdown links only
- No nested HTML or complex formatting

This reduces token usage when including in agent context.

### 4. Reference in Agent Prompts

Example agent prompt structure:

```
You are a development assistant following SDD (Specification-Driven Development).

MANDATES (Hard Rules):
<read from .sdd/source/mandates/mandates.md>

GUIDELINES (Best Practices):
<read from .sdd/source/guidelines/{{relevant-category}}.md>

TASK:
<your specific task>
```

## Pre-Cache Strategy

For optimal performance when using these with agents:

1. **Load once**: Read governance files once per session
2. **Cache in memory**: Store in agent context/memory
3. **Reference later**: Use markdown file references instead of re-reading
4. **Update on changes**: Re-read if .sdd/source files change

See `.sdd/runtime/README.md` for detailed pre-cache instructions.

## File Organization

### Mandates (Non-customizable)
- Location: `.sdd/source/mandates/mandates.md`
- Count: {mandate_count}
- Rule: **MUST** be followed (no exceptions)

### Guidelines (Customizable)
- Location: `.sdd/source/guidelines.dsl` and rendered `.sdd/source/guidelines/`
- Count: {guideline_count}
- Rule: Should be followed (exceptions allowed with documentation)

### Wizard Language Context

{language_context_lines}
### Surface Handling
- Mandatory surfaces such as technical documentation, governance artifacts, and CLI help remain governed by mandates.
- Contextual surfaces such as chat, operational UI, and local-only notes may follow wizard language preference when workspace policy allows it.
- `.analysis/` is treated as workspace-local documentation until content is promoted into canonical documentation or governance surfaces.

### Categories Covered

{categories_list}

## Next Steps

1. **Read Mandates**: Start with `.sdd/source/mandates/mandates.md`
2. **Browse Guidelines**: Review `.sdd/source/guidelines/` for your domain
3. **Use in Tasks**: Reference these when making decisions
4. **Cache Strategically**: Load once, reuse across multiple agent calls

---

**Generated by SDD Wizard v3.0**
"""


def build_runtime_readme(
    generated_at: str,
    language_context_lines: str,
    runtime_guideline_load_snippet: str,
) -> str:
    """Return the full .sdd/runtime/README.md content."""
    return f"""# .sdd/runtime - Agent Pre-Cache Strategy

⚡ **For AI Agents: Instructions on using .sdd/source as pre-cache**

## Overview

This directory provides guidance on how to use `.sdd/source/` as a **pre-cache**
mechanism for AI agents to reduce context token usage and improve performance.

**Generated**: {generated_at}

## Language Context

The wizard may capture language preference context for interaction surfaces.

{language_context_lines}Mandatory language rules still override preference context for:
- technical documentation
- governance artifacts
- CLI help and examples

## What is Pre-Caching?

Pre-caching is a strategy where:

1. Governance files are loaded **once** at the start of an agent session
2. Content is cached **in memory** (not re-read from disk)
3. Subsequent tasks **reference** the cached content instead of re-reading files

**Result**: Lower token usage, faster execution, consistent governance adherence.

## Pre-Cache Workflow

### Session Start (Agent Initialization)

```python
# When agent starts, load governance once
def init_agent():
    mandates = read_file('.sdd/source/mandates/mandates.md')
{runtime_guideline_load_snippet}
    # Cache in agent memory/context
    agent.context['mandates'] = mandates
    agent.context['guidelines'] = guidelines
```

### Task Execution (Reference, Don't Re-Read)

```python
# During task execution, reference cached content
def execute_task(task):
    relevant_category = determine_category(task)
    guideline = agent.context['guidelines'][relevant_category]

    # Use guideline in task execution
    # DO NOT re-read from .sdd/source
```

### Session End

- Cached content is available for entire agent session
- No disk reads for governance after initial load
- Only refresh if files are explicitly updated

## Integration with Agent Frameworks

### With LangChain/LlamaIndex

```python
from langchain.memory import ConversationBufferMemory

# Store governance in agent memory
agent.memory['mandates'] = read_governance('mandates')
agent.memory['guidelines'] = read_governance('guidelines')

# Use in prompts
system_prompt = f'''
You follow SDD governance.

MANDATES:
{{agent.memory['mandates']}}

GUIDELINES:
{{agent.memory['guidelines'][task_category]}}
'''
```

### With Custom Agents

```python
class SDDAgent:
    def __init__(self, project_root):
        self.governance = {{}}
        self.load_governance(project_root)

    def load_governance(self, project_root):
        '''Load governance once at startup'''
        source_dir = Path(project_root) / '.sdd' / 'source'

        self.governance['mandates'] = (source_dir / 'mandates' / 'mandates.md').read_text()
        self.governance['guidelines'] = {{}}

        for category_file in (source_dir / 'guidelines').glob('*.md'):
            category = category_file.stem
            self.governance['guidelines'][category] = category_file.read_text()

    def execute(self, task):
        '''Execute task with cached governance'''
        relevant_guideline = self.governance['guidelines'].get(task.category)
        # Use cached guideline
        return self.process_task(task, relevant_guideline)
```

## Memory Organization Strategy

### By Category (Recommended)

```
agent.memory = {{
    'mandates': <mandates_content>,
    'guidelines': {{
        'git': <git_guidelines>,
        'testing': <testing_guidelines>,
        'naming': <naming_guidelines>,
        'docs': <docs_guidelines>,
        'style': <style_guidelines>,
        'performance': <performance_guidelines>
    }},
    'last_updated': <timestamp>,
    'cache_validity': 86400  # 24 hours in seconds
}}
```

### By Usage Frequency (Alternative)

```
agent.memory = {{
    'frequent': {{
        'mandates': <mandates_content>,
        'git_guidelines': <git_guidelines>,
        'testing_guidelines': <testing_guidelines>
    }},
    'occasional': {{
        'naming_guidelines': <naming_guidelines>,
        'style_guidelines': <style_guidelines>
    }},
    'reference': {{
        'docs_guidelines': <docs_guidelines>,
        'performance_guidelines': <performance_guidelines>
    }}
}}
```

## Cache Invalidation

Re-read governance from `.sdd/source/` if:

1. **Manual update**: Files are explicitly updated by developer
2. **Time-based**: Cache expires (e.g., 24 hours)
3. **Version change**: Metadata indicates version change
4. **Explicit refresh**: Agent receives refresh command

Example cache validity check:

```python
def should_refresh_cache(agent):
    last_update = agent.memory.get('governance_updated')
    current_time = time.time()

    # Refresh if older than 24 hours or no timestamp
    cache_age = current_time - (last_update or 0)
    return cache_age > 86400
```

## Optimization Tips

### 1. Lazy Loading (For Large Governance)

Don't load all guidelines at once. Load on demand:

```python
def get_guideline(category):
    if category not in agent.memory.get('guidelines', {{}}):
        path = Path('.sdd/source/guidelines') / f'{{category}}.md'
        agent.memory['guidelines'][category] = path.read_text()
    return agent.memory['guidelines'][category]
```

### 2. Compression (For Token Efficiency)

Compress guidelines before caching:

```python
import gzip
import base64

def compress_guideline(content):
    compressed = gzip.compress(content.encode())
    return base64.b64encode(compressed).decode()

def decompress_guideline(encoded):
    compressed = base64.b64decode(encoded)
    return gzip.decompress(compressed).decode()
```

### 3. Summarization (For Context Window)

Create summaries instead of full files:

```python
# For each guideline, create a 1-paragraph summary
summaries = {{
    'git': 'Use conventional commits, protect main, PR reviews required, ...',
    'testing': 'Write tests first, >80% coverage required, run CI on all PRs, ...',
    ...
}}
```

## Troubleshooting

### Issue: Agent doesn't follow governance

**Solution**: Verify cache was loaded and is up-to-date
```python
print(agent.memory.get('governance_updated'))  # noqa: T201
print(len(agent.memory.get('mandates', '')))  # noqa: T201
```

### Issue: Out of memory with large governance

**Solution**: Use lazy loading or compression (see Optimization Tips)

### Issue: Stale governance after updates

**Solution**: Implement cache invalidation based on file mtime
```python
governance_mtime = Path('.sdd/source/mandates/mandates.md').stat().st_mtime
if governance_mtime > agent.memory.get('governance_loaded_at', 0):
    refresh_cache()
```

## Best Practices

1. ✅ **Load once per session** - Don't re-read governance files repeatedly
2. ✅ **Cache in memory** - Keep governance in agent context/memory
3. ✅ **Reference by category** - Use structured memory keys
4. ✅ **Implement cache invalidation** - Refresh on updates
5. ✅ **Monitor cache size** - Warn if governance grows too large
6. ✅ **Document cache strategy** - Clarify to team how governance is cached

## Metrics to Track

- Cache hit rate (% of requests using cached vs fresh)
- Average token savings per session
- Cache refresh frequency
- Cache size in memory

---

**Generated by SDD Wizard v3.0**
"""
