"""Template builder for .sdd/source/README.md."""

from __future__ import annotations


def build_source_readme(
    generated_at: str,
    language: str,
    adoption_level: str,
    guideline_category_block: str,
    guideline_read_examples: str,
    language_context_lines: str,
    categories_list: str,
    mandate_count: int,
    guideline_count: int,
) -> str:
    """Return the full .sdd/source/README.md content."""
    return f"""# .sdd/source - Governance Source of Truth

⚡ **For AI Agents: This is your primary query directory**

## Overview

This directory contains the **compiled and optimized** governance specifications that agents should reference.

**Generated**: {generated_at}
**Language**: {language}
**Adoption Level**: {adoption_level}

## Directory Structure

```
.sdd/source/
├── mandates/
│   └── mandates.md              ← Read mandates first (hard rules)
├── guidelines.dsl               ← Guideline source of truth (universal + tagged)
├── guidelines/
{guideline_category_block}└── README.md                    ← This file
```

## For AI Agents: How to Use This

### 1. Query Mandates First

Always read `.sdd/source/mandates/mandates.md` to understand **hard rules** that CANNOT be customized.

```
cat .sdd/source/mandates/mandates.md
```

### 2. Query Relevant Guidelines

Based on the task, read relevant guidelines:

```
# Full DSL source
cat .sdd/source/guidelines.dsl

# Example rendered category files
{guideline_read_examples}```

### 3. Use As Pre-Cache Context

These files are **optimized for AI parsing** (IA-FIRST format):
- Flat hierarchy (H2 sections, no skipped levels)
- Clear lists instead of prose
- Emoji markers for decisions
- Markdown links only
- No nested HTML or complex formatting

This reduces token usage when including in agent context.

### 4. Reference in Agent Prompts

Example agent prompt structure:

```
You are a development assistant following SDD (Specification-Driven Development).

MANDATES (Hard Rules):
<read from .sdd/source/mandates/mandates.md>

GUIDELINES (Best Practices):
<read from .sdd/source/guidelines/{{relevant-category}}.md>

TASK:
<your specific task>
```

## Pre-Cache Strategy

For optimal performance when using these with agents:

1. **Load once**: Read governance files once per session
2. **Cache in memory**: Store in agent context/memory
3. **Reference later**: Use markdown file references instead of re-reading
4. **Update on changes**: Re-read if .sdd/source files change

See `.sdd/runtime/README.md` for detailed pre-cache instructions.

## File Organization

### Mandates (Non-customizable)
- Location: `.sdd/source/mandates/mandates.md`
- Count: {mandate_count}
- Rule: **MUST** be followed (no exceptions)

### Guidelines (Customizable)
- Location: `.sdd/source/guidelines.dsl` and rendered `.sdd/source/guidelines/`
- Count: {guideline_count}
- Rule: Should be followed (exceptions allowed with documentation)

### Wizard Language Context

{language_context_lines}
### Surface Handling
- Mandatory surfaces such as technical documentation, governance artifacts, and CLI help remain governed by mandates.
- Contextual surfaces such as chat, operational UI, and local-only notes may follow wizard language preference when workspace policy allows it.
- `.analysis/` is treated as workspace-local documentation until content is promoted into canonical documentation or governance surfaces.

### Categories Covered

{categories_list}

## Next Steps

1. **Read Mandates**: Start with `.sdd/source/mandates/mandates.md`
2. **Browse Guidelines**: Review `.sdd/source/guidelines/` for your domain
3. **Use in Tasks**: Reference these when making decisions
4. **Cache Strategically**: Load once, reuse across multiple agent calls

---

**Generated by SDD Wizard v3.0**
"""
