#!/usr/bin/env python3
"""
PHASE 3: Load and Integrate Compiled Governance from compiled/

Loads governance-core.json and governance-client.json generated by PHASE 2 compiler.
Validates fingerprints to ensure integrity.
Integrates with wizard orchestration pipeline.

Input:
  - compiled/governance-core.json (34 items)
  - compiled/governance-client.json (121 items)
  - user_selections.json (routing instructions)

Output:
  - Validated governance data ready for wizard phases
  - Fingerprint verification reports
"""

import hashlib
import json
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).parent.parent))


def _calculate_fingerprint(data: dict[str, Any]) -> str:
    """Calculate SHA256 fingerprint of data dict, excluding fingerprint fields."""
    data_copy = {
        k: v
        for k, v in data.items()
        if k not in ["fingerprint", "fingerprintpackages_salt"]
    }
    return hashlib.sha256(
        json.dumps(data_copy, sort_keys=True).encode("utf-8")
    ).hexdigest()


def _calculate_client_fp(client_data: dict[str, Any]) -> str:
    """Calculate client fingerprint with salt included (PipelineBuilder convention)."""
    data = {k: v for k, v in client_data.items() if k != "fingerprint"}
    return hashlib.sha256(json.dumps(data, sort_keys=True).encode("utf-8")).hexdigest()


def _load_governance_metadata(
    compiled_dir: Path,
) -> tuple[dict[str, Any], dict[str, Any]]:
    """Load audit metadata JSON files; raises on failure."""
    metadata_core = compiled_dir / "audit" / "metadata-core.json"
    if not metadata_core.exists():
        metadata_core = compiled_dir / "metadata-core.json"
    with open(metadata_core, encoding="utf-8") as f:
        meta_core: dict[str, Any] = json.load(f)
    with open(compiled_dir / "metadata-client.json", encoding="utf-8") as f:
        meta_client: dict[str, Any] = json.load(f)
    return meta_core, meta_client


class GovernanceLoader:
    """Load and validate governance files from compiled/"""

    def __init__(self, repo_root: Path | None = None, verbose: bool = False):
        self.repo_root = Path(repo_root or Path.cwd())
        self.compiled_dir = self.repo_root / "compiler" / "compiled"
        self.verbose = verbose
        self.core_data: dict[str, Any] | None = None
        self.client_data: dict[str, Any] | None = None
        self.metadatapackages: dict[str, Any] | None = None
        self.metadata_client: dict[str, Any] | None = None

    def log(self, message: str, level: str = "INFO") -> None:
        """Log message"""
        if level == "INFO" or self.verbose:
            print(f"  {level:8s} {message}")  # noqa: T201

    def load_files(self) -> bool:  # noqa: C901
        """Load governance JSON files"""
        self.log("Loading governance-core.json...")

        core_path = self.compiled_dir / "governance-core.json"
        if not core_path.exists():
            self.log(f"❌ File not found: {core_path}", "ERROR")
            return False

        try:
            with open(core_path, encoding="utf-8") as f:
                self.core_data = json.load(f)
            self.log(f"✓ Loaded {len(self.core_data.get('items', []))} core items")
        except json.JSONDecodeError as e:
            self.log(f"❌ JSON parse error in governance-core.json: {e}", "ERROR")
            return False

        self.log("Loading governance-client.json...")

        client_path = self.compiled_dir / "governance-client.json"
        if not client_path.exists():
            self.log(f"❌ File not found: {client_path}", "ERROR")
            return False

        try:
            with open(client_path, encoding="utf-8") as f:
                self.client_data = json.load(f)
            self.log(f"✓ Loaded {len(self.client_data.get('items', []))} client items")
        except json.JSONDecodeError as e:
            self.log(f"❌ JSON parse error in governance-client.json: {e}", "ERROR")
            return False

        try:
            self.metadatapackages, self.metadata_client = _load_governance_metadata(
                self.compiled_dir
            )
        except Exception as e:
            self.log(f"⚠️  Could not load metadata files: {e}", "WARN")

        return True

    def validate_fingerprints(self) -> tuple[bool, dict[str, Any]]:
        """Validate fingerprints using SALT strategy"""
        report: dict[str, Any] = {
            "core_fingerprint_valid": False,
            "client_fingerprint_valid": False,
            "salt_strategy_valid": False,
            "core_fp": None,
            "client_fp": None,
            "core_salt": None,
        }

        if not self.core_data or not self.client_data:
            self.log("❌ Data not loaded", "ERROR")
            return False, report

        self.log("Validating fingerprints...")

        # Verify core fingerprint
        core_fp_stored = str(self.core_data.get("fingerprint") or "")
        core_fp_calculated = _calculate_fingerprint(self.core_data)

        if core_fp_stored == core_fp_calculated:
            self.log("✓ Core fingerprint valid")
            report["core_fingerprint_valid"] = True
            report["core_fp"] = core_fp_stored
        else:
            self.log("❌ Core fingerprint mismatch!", "ERROR")
            self.log(f"   Expected: {core_fp_stored[:16]}...", "ERROR")
            self.log(f"   Got:      {core_fp_calculated[:16]}...", "ERROR")
            return False, report

        # Verify client fingerprint (SALT strategy)
        client_fp_stored = str(self.client_data.get("fingerprint") or "")
        client_salt = str(self.client_data.get("fingerprintpackages_salt") or "")
        # NOTE: Client FP is calculated WITH the salt included (from PipelineBuilder)
        client_fp_calculated = _calculate_client_fp(self.client_data)

        if client_fp_stored == client_fp_calculated:
            self.log("✓ Client fingerprint valid")
            report["client_fingerprint_valid"] = True
            report["client_fp"] = client_fp_stored
        else:
            self.log("❌ Client fingerprint mismatch!", "ERROR")
            self.log(f"   Expected: {client_fp_stored[:16]}...", "ERROR")
            self.log(f"   Got:      {client_fp_calculated[:16]}...", "ERROR")
            return False, report

        # Verify SALT strategy
        if client_salt == core_fp_stored:
            self.log("✓ SALT strategy verified (client salt == core fingerprint)")
            report["salt_strategy_valid"] = True
            report["core_salt"] = client_salt
        else:
            self.log("❌ SALT strategy broken!", "ERROR")
            self.log(f"   Core FP:   {core_fp_stored[:16]}...", "ERROR")
            self.log(f"   Client Salt: {client_salt[:16]}...", "ERROR")
            return False, report

        return True, report

    def extract_mandates(self) -> dict[str, dict[str, Any]]:
        """Extract mandates from sdd_core"""
        mandates: dict[str, dict[str, Any]] = {}
        if self.core_data is None:
            return mandates
        for item in self.core_data.get("items", []):
            if item["type"] == "MANDATE":
                mandates[item["id"]] = {
                    "id": item["id"],
                    "title": item["title"],
                    "criticality": item["criticality"],
                    "category": item["category"],
                    "source": "core",
                }
        return mandates

    def extract_guidelines(
        self,
    ) -> tuple[dict[str, dict[str, Any]], dict[str, dict[str, Any]]]:
        """Extract guidelines from both core and client"""
        core_guidelines: dict[str, dict[str, Any]] = {}
        client_guidelines: dict[str, dict[str, Any]] = {}

        if self.core_data is None or self.client_data is None:
            return core_guidelines, client_guidelines

        # Core guidelines
        for item in self.core_data.get("items", []):
            if item["type"] == "GUIDELINE":
                core_guidelines[item["id"]] = {
                    "id": item["id"],
                    "title": item["title"],
                    "criticality": item["criticality"],
                    "category": item["category"],
                    "customizable": item["customizable"],
                    "source": "core",
                }

        # Client guidelines
        for item in self.client_data.get("items", []):
            if item["type"] == "GUIDELINE":
                client_guidelines[item["id"]] = {
                    "id": item["id"],
                    "title": item["title"],
                    "criticality": item["criticality"],
                    "category": item["category"],
                    "customizable": item["customizable"],
                    "source": "client",
                }

        return core_guidelines, client_guidelines

    def extract_all_governance(self) -> dict[str, Any]:
        """Extract complete governance structure"""
        core_data = self.core_data or {}
        client_data = self.client_data or {}
        return {
            "core": {
                "items": core_data.get("items", []),
                "fingerprint": core_data.get("fingerprint"),
                "metadata": self.metadatapackages,
            },
            "client": {
                "items": client_data.get("items", []),
                "fingerprint": client_data.get("fingerprint"),
                "fingerprintpackages_salt": client_data.get("fingerprintpackages_salt"),
                "metadata": self.metadata_client,
            },
        }


def phase_2_load_compiled_v3(
    repo_root: Path | None = None,
) -> tuple[bool, dict[str, Any]]:
    """
    PHASE 2 (v3): Load compiled governance from compiled/

    IMPORTANT: Returns wizard-compatible report structure for orchestration pipeline.

    Returns:
        Tuple[bool, Dict]: (success, report)
    """
    print()  # noqa: T201
    print("=" * 100)  # noqa: T201
    print("PHASE 2 (v3): LOAD COMPILED GOVERNANCE")  # noqa: T201
    print("=" * 100)  # noqa: T201
    print()  # noqa: T201

    repo_root = repo_root or Path.cwd()
    # Initialize wizard-compatible report
    report: dict[str, Any] = {
        "phase": "PHASE_2_LOAD_COMPILED",
        "status": "PENDING",
        "checks": {
            "core_json_exists": False,
            "client_json_exists": False,
            "fingerprint_validation": False,
            "data_extraction": False,
        },
        "data": {
            "mandate": {},
            "guidelines": {},
        },
        "statistics": {
            "mandate_count": 0,
            "core_guideline_count": 0,
            "client_guideline_count": 0,
            "core_fingerprint": "",
            "client_fingerprint": "",
        },
        "errors": [],
        "warnings": [],
        "_artifacts": {},
    }

    loader = GovernanceLoader(repo_root, verbose=False)

    # Load files
    if not loader.load_files():
        report["errors"].append("Failed to load governance JSON files")
        report["status"] = "FAILED"
        return False, report

    report["checks"]["core_json_exists"] = True
    report["checks"]["client_json_exists"] = True

    print()  # noqa: T201
    print("🔐 FINGERPRINT VALIDATION")  # noqa: T201
    print("-" * 100)  # noqa: T201

    # Validate fingerprints
    valid, fp_report = loader.validate_fingerprints()

    if not valid:
        report["errors"].append("Fingerprint validation failed")
        report["status"] = "FAILED"
        print()  # noqa: T201
        return False, report

    report["checks"]["fingerprint_validation"] = True
    report["statistics"]["core_fingerprint"] = fp_report.get("core_fp", "")[:16] + "..."
    report["statistics"]["client_fingerprint"] = (
        fp_report.get("client_fp", "")[:16] + "..."
    )

    print()  # noqa: T201
    print("✅ All fingerprints validated!")  # noqa: T201
    print()  # noqa: T201

    # Extract governance
    mandates = loader.extract_mandates()
    core_guidelines, client_guidelines = loader.extract_guidelines()
    all_governance = loader.extract_all_governance()

    # Combine mandates and guidelines for wizard compatibility
    report["data"]["mandate"] = mandates
    report["data"]["guidelines"] = {}
    report["data"]["guidelines"].update(
        {f"core_{k}": v for k, v in core_guidelines.items()}
    )
    report["data"]["guidelines"].update(
        {f"client_{k}": v for k, v in client_guidelines.items()}
    )

    report["statistics"]["mandate_count"] = len(mandates)
    report["statistics"]["core_guideline_count"] = len(core_guidelines)
    report["statistics"]["client_guideline_count"] = len(client_guidelines)

    # Store artifacts for downstream phases
    report["_artifacts"]["mandates"] = mandates
    report["_artifacts"]["core_guidelines"] = core_guidelines
    report["_artifacts"]["client_guidelines"] = client_guidelines
    report["_artifacts"]["governance"] = all_governance
    report["_artifacts"]["fingerprints"] = fp_report

    report["checks"]["data_extraction"] = True
    report["status"] = "SUCCESS"

    return True, report


if __name__ == "__main__":
    success, report = phase_2_load_compiled_v3()

    if success:
        print("\n✅ PHASE 2 (v3) COMPLETE")  # noqa: T201
        print(f"   Mandates: {report['mandates_count']}")  # noqa: T201
        print(f"   Core Guidelines: {report['core_guidelines_count']}")  # noqa: T201
        print(f"   Client Guidelines: {report['client_guidelines_count']}")  # noqa: T201
        print(f"   Total Items: {report['total_items']}")  # noqa: T201
    else:
        print(f"\n❌ PHASE 2 (v3) FAILED: {report.get('error')}")  # noqa: T201
        sys.exit(1)
