"""Phase 7 Validate Output."""

import json
from pathlib import Path
from typing import Any

"""Phase 7: Validate generated output

Validates that the generated project meets all requirements and has proper structure
"""


def _validate_directory_structure(project_dir: Path) -> tuple[bool, list[str]]:
    """Validate that all required directories exist

    Returns:
        (all_valid, messages)
    """
    required_dirs = [
        ".sdd/CANONICAL",
        "guidelines",
        "src",
        "tests",
        "docs",
    ]

    messages = []
    all_valid = True

    for dir_name in required_dirs:
        dir_path = project_dir / dir_name
        if dir_path.exists() and dir_path.is_dir():
            messages.append(f"✓ Directory exists: {dir_name}")
        else:
            messages.append(f"✗ Missing directory: {dir_name}")
            all_valid = False

    return (all_valid, messages)


def _validate_required_files(project_dir: Path) -> tuple[bool, list[str]]:
    """Validate that all required files exist

    Returns:
        (all_valid, messages)
    """
    required_files = {
        ".sdd/CANONICAL/mandate.spec": "Mandate specification",
        ".sdd/CANONICAL/guidelines.dsl": "Guidelines specification",
        ".sdd/CANONICAL/metadata.json": "Project metadata",
        "guidelines/README.md": "Guidelines index",
        "README.md": "Project README",
    }

    messages = []
    all_valid = True

    for file_path, description in required_files.items():
        full_path = project_dir / file_path
        if full_path.exists() and full_path.is_file():
            size = full_path.stat().st_size
            messages.append(f"✓ {description}: {file_path} ({size} bytes)")
        else:
            messages.append(f"✗ Missing: {description} ({file_path})")
            all_valid = False

    return (all_valid, messages)


def _validate_file_contents(project_dir: Path) -> tuple[bool, list[str]]:
    """Validate that files have content (not empty)

    Returns:
        (all_valid, messages)
    """
    check_files = [
        ".sdd/CANONICAL/mandate.spec",
        ".sdd/CANONICAL/guidelines.dsl",
        ".sdd/CANONICAL/metadata.json",
        "guidelines/README.md",
        "README.md",
    ]

    messages = []
    all_valid = True

    for file_path in check_files:
        full_path = project_dir / file_path
        if full_path.exists():
            content = full_path.read_text(encoding="utf-8")
            if content.strip():
                lines = len(content.split("\n"))
                messages.append(f"✓ Content valid: {file_path} ({lines} lines)")
            else:
                messages.append(f"✗ Empty file: {file_path}")
                all_valid = False

    return (all_valid, messages)


def _validate_metadata_integrity(project_dir: Path) -> tuple[bool, list[str]]:
    """Validate metadata.json is valid and contains required fields

    Returns:
        (all_valid, messages)
    """
    messages = []
    all_valid = True

    metadata_file = project_dir / ".sdd/CANONICAL/metadata.json"

    if not metadata_file.exists():
        messages.append("✗ metadata.json not found")
        return (False, messages)

    try:
        metadata = json.loads(metadata_file.read_text(encoding="utf-8"))

        # Check required fields (v3.0: no version field, no retrocompat needed)
        required_fields = ["generated_at"]
        for field in required_fields:
            if field in metadata:
                messages.append(f"✓ Metadata field present: {field}")
            else:
                messages.append(f"✗ Missing metadata field: {field}")
                all_valid = False

        # Additional checks
        if "generation_phase" in metadata:
            messages.append(f"✓ Generated by: {metadata.get('generation_phase')}")

        return (all_valid, messages)

    except json.JSONDecodeError as e:
        messages.append(f"✗ Invalid JSON in metadata.json: {e}")
        return (False, messages)
    except Exception as e:
        messages.append(f"✗ Error validating metadata: {e}")
        return (False, messages)


def _validate_specifications(project_dir: Path) -> tuple[bool, list[str]]:
    """Validate specification files are readable

    Returns:
        (all_valid, messages)
    """
    messages = []
    all_valid = True

    # Validate mandate.spec
    mandate_file = project_dir / ".sdd/CANONICAL/mandate.spec"
    if mandate_file.exists():
        try:
            content = mandate_file.read_text(encoding="utf-8")
            if "{" in content and "}" in content:
                messages.append("✓ mandate.spec is readable and has DSL content")
            else:
                messages.append("⚠ mandate.spec may not be valid DSL")
        except Exception as e:
            messages.append(f"✗ Error reading mandate.spec: {e}")
            all_valid = False

    # Validate guidelines.dsl
    guidelines_file = project_dir / ".sdd/CANONICAL/guidelines.dsl"
    if guidelines_file.exists():
        try:
            content = guidelines_file.read_text(encoding="utf-8")
            if "{" in content or len(content) > 100:  # Should have some content
                messages.append("✓ guidelines.dsl is readable and has content")
            else:
                messages.append("⚠ guidelines.dsl may be incomplete")
        except Exception as e:
            messages.append(f"✗ Error reading guidelines.dsl: {e}")
            all_valid = False

    return (all_valid, messages)


def _validate_build_files(project_dir: Path) -> tuple[bool, list[str]]:
    """Validate language-specific build files

    Returns:
        (all_valid, messages)
    """
    messages = []
    all_valid = True

    # Check for language-specific files
    if (project_dir / "pom.xml").exists():
        try:
            content = (project_dir / "pom.xml").read_text(encoding="utf-8")
            if "<?xml" in content and "<project" in content:
                messages.append("✓ pom.xml is valid XML")
            else:
                messages.append("⚠ pom.xml may not be valid")
        except Exception as e:
            messages.append(f"✗ Error reading pom.xml: {e}")

    if (project_dir / "requirements.txt").exists():
        messages.append("✓ requirements.txt found")

    if (project_dir / "pyproject.toml").exists():
        messages.append("✓ pyproject.toml found")

    if (project_dir / "package.json").exists():
        try:
            json.loads((project_dir / "package.json").read_text(encoding="utf-8"))
            messages.append("✓ package.json is valid JSON")
        except Exception as e:
            messages.append(f"✗ Invalid package.json: {e}")

    return (all_valid, messages)


def _count_guideline_files(project_dir: Path) -> tuple[int, int]:
    """Count generated guideline markdown files

    Returns:
        (count, expected_minimum)
    """
    guidelines_dir = project_dir / "guidelines"

    if not guidelines_dir.exists():
        return (0, 1)

    md_files = list(guidelines_dir.glob("*.md"))
    # Should have at least README.md
    return (len(md_files), 1)


def phase_7_validate_output(
    project_dir: Path, repo_root: Path | None = None
) -> tuple[bool, dict[str, Any]]:
    """Validate generated project output

    Args:
        project_dir: Generated project directory
        repo_root: Repository root

    Returns:
        (success, report)
    """
    report: dict[str, Any] = {
        "phase": "PHASE_7_VALIDATE_OUTPUT",
        "status": "PENDING",
        "data": {},
        "validation_results": {
            "directory_structure": False,
            "required_files": False,
            "file_contents": False,
            "metadata_integrity": False,
            "specifications": False,
            "build_files": True,  # Optional
        },
        "checks_passed": 0,
        "checks_total": 6,
        "warnings": [],
        "errors": [],
        "details": [],
    }

    try:
        if not project_dir.exists():
            report["errors"].append(f"Project directory not found: {project_dir}")
            report["status"] = "FAILED"
            return (False, report)

        # 1. Validate directory structure
        success, messages = _validate_directory_structure(project_dir)
        report["validation_results"]["directory_structure"] = success
        report["details"].extend(messages)
        if success:
            report["checks_passed"] += 1
        else:
            report["warnings"].extend(messages)

        # 2. Validate required files
        success, messages = _validate_required_files(project_dir)
        report["validation_results"]["required_files"] = success
        report["details"].extend(messages)
        if success:
            report["checks_passed"] += 1
        else:
            report["errors"].extend(messages)

        # 3. Validate file contents
        success, messages = _validate_file_contents(project_dir)
        report["validation_results"]["file_contents"] = success
        report["details"].extend(messages)
        if success:
            report["checks_passed"] += 1
        else:
            report["warnings"].extend(messages)

        # 4. Validate metadata
        success, messages = _validate_metadata_integrity(project_dir)
        report["validation_results"]["metadata_integrity"] = success
        report["details"].extend(messages)
        if success:
            report["checks_passed"] += 1
        else:
            report["warnings"].extend(messages)

        # 5. Validate specifications
        success, messages = _validate_specifications(project_dir)
        report["validation_results"]["specifications"] = success
        report["details"].extend(messages)
        if success:
            report["checks_passed"] += 1
        else:
            report["warnings"].extend(messages)

        # 6. Validate build files
        success, messages = _validate_build_files(project_dir)
        report["details"].extend(messages)

        # Check guideline files
        guideline_count, expected_min = _count_guideline_files(project_dir)
        report["details"].append(
            f"✓ Generated {guideline_count} guideline markdown files"
        )

        # Determine overall success
        critical_checks = [
            report["validation_results"]["directory_structure"],
            report["validation_results"]["required_files"],
            report["validation_results"]["metadata_integrity"],
        ]

        overall_success = all(critical_checks)

        report["data"] = {
            "project_dir": str(project_dir),
            "validation_passed": report["checks_passed"],
            "validation_total": report["checks_total"],
            "all_checks_passed": overall_success,
            "guideline_files": guideline_count,
        }

        if overall_success:
            report["status"] = "SUCCESS"
        else:
            report["status"] = "FAILED"

        return (overall_success, report)

    except Exception as e:
        report["errors"].append(str(e))
        report["status"] = "FAILED"
        return (False, report)
