"""Source README compiler for Phase 3 .sdd/source output."""

from __future__ import annotations

import traceback
from collections.abc import Callable
from datetime import datetime
from pathlib import Path
from typing import Any


class SourceReadmeCompiler:
    """Write the AI-agent README.md for .sdd/source."""

    def __init__(
        self,
        output_path: Path,
        language: str = "Python",
        emitter: Callable[[str], None] | None = None,
    ) -> None:
        self._output_path = output_path
        self._language = language
        self._emit = emitter or print

    def write(
        self,
        mandates: list[dict[str, Any]],
        guidelines: list[dict[str, Any]],
    ) -> bool:
        """Generate README.md under output_path/source/."""
        try:
            source_dir = self._output_path / "source"
            source_dir.mkdir(parents=True, exist_ok=True)

            categories = sorted(
                set(g.get("category", "general") for g in guidelines)
            ) or ["general"]
            categories_list = "\n".join(f"- {cat.title()}" for cat in categories)
            first_cat = categories[0]
            second_cat = categories[1] if len(categories) > 1 else "other"

            content = f"""# .sdd/source - Governance Source of Truth

⚡ **For AI Agents: This is your primary query directory**

## Overview

This directory contains the **compiled and optimized** governance specifications that agents should reference.

**Generated**: {datetime.now().isoformat()}
**Language**: {self._language}

## Directory Structure

```
.sdd/source/
├── mandates/
│   └── mandates.md              ← Read mandates first (hard rules)
├── guidelines/
│   ├── {first_cat}.md
│   ├── {second_cat}.md
│   └── (organized by category)
└── README.md                    ← This file
```

## For AI Agents: How to Use This

### 1. Query Mandates First

Always read `.sdd/source/mandates/mandates.md` to understand **hard rules** that CANNOT be customized.

### 2. Query Relevant Guidelines

Based on the task, read relevant guidelines from `.sdd/source/guidelines/`.

### 3. Use As Pre-Cache Context

These files are **optimized for AI parsing** (IA-FIRST format).

## File Organization

### Mandates (Non-customizable)
- Location: `.sdd/source/mandates/mandates.md`
- Count: {len(mandates)}

### Guidelines (Customizable)
- Location: `.sdd/source/guidelines/`
- Count: {len(guidelines)}

### Categories Covered

{categories_list}

---

**Generated by SDD Wizard v3.0**
"""

            (source_dir / "README.md").write_text(content, encoding="utf-8")
            return True
        except Exception as exc:
            self._emit(f"  ❌ Error generating source README: {exc}")
            traceback.print_exc()
            return False
