"""
Source Spec Bootstrapper - Clean environment spec generation for governance compilation.

Handles best-effort bootstrap of PHASE 1 source files (mandate.spec, guidelines.dsl)
in clean environments (CI, Docker) where docs-meta hasn't been generated yet.
"""

import logging
import re
from collections.abc import Callable
from pathlib import Path

logger = logging.getLogger(__name__)

_UNIVERSAL_LANGUAGE_GUIDELINES = """# Generated by SourceSpecBootstrapper

guideline G021 {
  type: SOFT
  title: "Language Preference Context — Interaction Surfaces"
  description: "User-declared language preference from the wizard should guide chat and operational UI surfaces when those surfaces are not persisted as technical documentation or governance artifacts."
  category: communication
  mandate_ref: M011
  examples: ["Wizard preference pt-BR -> agent chat and operational prompts may use pt-BR", "Persisted technical ADR in pt-BR -> VIOLATION because M011 still applies"]
}

guideline G022 {
  type: SOFT
  title: "Language Preference Context — Workspace-Local Notes"
  description: "Workspace-local notes and analysis artifacts may follow explicit user preference when the workspace classifies them as local documentation rather than canonical technical documentation."
  category: documentation
  mandate_ref: M011
  examples: [".analysis note in pt-BR with local-only intent -> CONTEXTUAL", "Canonical governance artifact in pt-BR -> VIOLATION because M011 still applies"]
}

guideline G023 {
  type: SOFT
  title: "Git Safety Practices"
  description: "Operational guidance for git command safety under M010 parallel-state assumption. Before any mutating action: run git status/diff first. Prefer direct file edits over git workflow commands. Do not stash, commit, cherry-pick, or push automatically — provide a summary and suggested commit message instead. Treat uncommitted work as potentially belonging to parallel agents or developers. Before any restricted command, state what it does, why it is needed, what state it may affect, and whether safer alternatives exist."
  category: governance
  mandate_ref: M010
  examples: ["After completing work: provide summary + suggested commit message, do not run git commit -> OK", "Before git stash: explain impact on parallel work, wait for approval -> OK", "git stash pop without asking -> VIOLATION", "git commit after task completion without explicit user instruction -> VIOLATION", "git status to inspect state before proposing action -> OK"]
}
"""


class SourceSpecBootstrapper:
    """Bootstraps governance source specs in clean environments."""

    def __init__(
        self,
        spec_path: Path,
        repo_root: Path,
        emit: Callable[[str], None] | None = None,
    ):
        """
        Initialize bootstrapper.

        Args:
            spec_path: Path to source spec directory.
            repo_root: Root of the repository.
            emit: Optional callback for status messages.
        """
        self.spec = spec_path
        self.repo_root = repo_root
        self._emit = emit

    def _out(self, message: str) -> None:
        """Emit status message via logger and optional callback."""
        logger.info(message)
        if self._emit is not None:
            self._emit(message)

    def has_source_specs(self) -> bool:
        """Return True when PHASE 1 source files are available."""
        return any(
            (self.spec / name).exists() for name in ("mandate.spec", "mandate.md")
        )

    def bootstrap(self) -> None:
        """
        Best-effort bootstrap for source specs in clean environments.

        Falls back to lightweight extraction from docs markdown when source
        specs are missing (e.g., CI, Docker, fresh clone).
        """
        if self.has_source_specs():
            return

        self.spec.mkdir(parents=True, exist_ok=True)
        self._bootstrap_from_markdown()

    def _extract_canonical_titles(self) -> dict[str, str]:
        """Scan docs/spec/canonical/ for mandate files and extract proper titles.

        Reads each *.md file that contains '# Mandate:' and '**ID:** M*' fields,
        returning a mapping of {mandate_id: title}. Files are sorted by path so
        results are deterministic across platforms (earlier path wins on conflicts).
        """
        canonical_root = self.repo_root / "docs" / "spec" / "canonical"
        title_map: dict[str, str] = {}
        if not canonical_root.exists():
            return title_map
        id_pattern = re.compile(r"^\*\*ID:\*\*\s*(M\d{3})", re.MULTILINE)
        title_pattern = re.compile(r"^#\s+(?:Mandate:)?\s*(.+)$", re.MULTILINE)
        for md_file in sorted(canonical_root.rglob("*.md")):
            try:
                content = md_file.read_text(encoding="utf-8", errors="ignore")
            except Exception:  # nosec B112
                continue
            id_match = id_pattern.search(content)
            title_match = title_pattern.search(content)
            if id_match and title_match:
                mid = id_match.group(1)
                title = title_match.group(1).strip()
                if mid not in title_map:
                    title_map[mid] = title
        return title_map

    def _bootstrap_from_markdown(self) -> None:
        """Generate mandate.md / guidelines.dsl from canonical spec files only.

        Uses only files with explicit **ID:** M* declarations (canonical mandate
        definitions), so documentation references to mandate IDs are not
        mistaken for mandate definitions. Guidelines are not auto-discovered
        to avoid false positives from spec documents.
        """
        docs_root = self.repo_root / "docs"
        if not docs_root.exists():
            return

        canonical_titles = self._extract_canonical_titles()
        mandate_ids = set(canonical_titles.keys())

        if not mandate_ids:
            return

        mandate_md = self.spec / "mandate.md"
        if not mandate_md.exists():
            lines = ["# Mandates - SDD v3.0", ""]
            for mandate_id in sorted(mandate_ids):
                title = canonical_titles.get(mandate_id, mandate_id)
                lines.append(f"## {mandate_id}: {title}")
                lines.append("")
            mandate_md.write_text("\n".join(lines), encoding="utf-8")

        # Write only universal bootstrap-safe guidelines. We still avoid broad
        # guideline auto-discovery from docs because G-IDs appear in examples,
        # ranges, and implementation notes that are not canonical definitions.
        guidelines_dsl = self.spec / "guidelines.dsl"
        if not guidelines_dsl.exists():
            guidelines_dsl.write_text(_UNIVERSAL_LANGUAGE_GUIDELINES, encoding="utf-8")

        if self.has_source_specs():
            self._out("  ℹ️  Bootstrapped docs-meta from markdown scan")
