"""
Source Spec Bootstrapper - Clean environment spec generation for governance compilation.

Handles best-effort bootstrap of PHASE 1 source files (mandate.spec, guidelines.dsl)
in clean environments (CI, Docker) where docs-meta hasn't been generated yet.
"""

import logging
import re
from collections.abc import Callable
from pathlib import Path

from sdd_core.utils.process import SafeProcessRunner

logger = logging.getLogger(__name__)


class SourceSpecBootstrapper:
    """Bootstraps governance source specs in clean environments."""

    def __init__(
        self,
        spec_path: Path,
        repo_root: Path,
        emit: Callable[[str], None] | None = None,
    ):
        """
        Initialize bootstrapper.

        Args:
            spec_path: Path to source spec directory.
            repo_root: Root of the repository.
            emit: Optional callback for status messages.
        """
        self.spec = spec_path
        self.repo_root = repo_root
        self._emit = emit

    def _out(self, message: str) -> None:
        """Emit status message via logger and optional callback."""
        logger.info(message)
        if self._emit is not None:
            self._emit(message)

    def has_source_specs(self) -> bool:
        """Return True when PHASE 1 source files are available."""
        return any(
            (self.spec / name).exists() for name in ("mandate.spec", "mandate.md")
        )

    def bootstrap(self) -> None:
        """
        Best-effort bootstrap for docs-meta sources in clean environments.

        Order:
        1) Reuse `sdd docs update` implementation if available.
        2) Fallback to lightweight extraction from docs markdown.
        """
        if self.has_source_specs():
            return

        self.spec.mkdir(parents=True, exist_ok=True)

        if self._bootstrap_via_docs_update():
            return

        self._bootstrap_from_markdown()

    def _bootstrap_via_docs_update(self) -> bool:
        """Try to generate docs-meta artifacts by invoking `sdd docs update` internals."""
        try:
            result = SafeProcessRunner().run(
                ["sdd", "docs", "update"],
                cwd=self.repo_root,
                check=False,
                capture_output=True,
            )
            if result.returncode == 0 and self.has_source_specs():
                self._out("  ℹ️  Bootstrapped docs-meta via `sdd docs update`")
                return True
        except Exception as exc:
            logger.debug("Docs update bootstrap failed: %s", exc)
        return False

    def _bootstrap_from_markdown(self) -> None:
        """Generate minimal mandate.spec / guidelines.dsl from docs markdown IDs."""
        docs_root = self.repo_root / "docs"
        if not docs_root.exists():
            return

        mandate_ids: set[str] = set()
        guideline_ids: set[str] = set()

        for markdown_file in docs_root.rglob("*.md"):
            try:
                content = markdown_file.read_text(encoding="utf-8", errors="ignore")
            except Exception:  # nosec B112 — intentional: unreadable files are skipped
                continue
            mandate_ids.update(re.findall(r"\bM\d{3}\b", content))
            guideline_ids.update(re.findall(r"\bG\d{3}\b", content))

        if not mandate_ids:
            return

        mandate_spec = self.spec / "mandate.spec"
        if not mandate_spec.exists():
            mandate_lines = ["# Generated by SourceSpecBootstrapper", ""]
            for mandate_id in sorted(mandate_ids):
                mandate_lines.append(
                    f"- [{mandate_id}] **Auto-discovered {mandate_id}**"
                )
            mandate_spec.write_text("\n".join(mandate_lines) + "\n", encoding="utf-8")

        guidelines_dsl = self.spec / "guidelines.dsl"
        if not guidelines_dsl.exists():
            guideline_lines = ["# Generated by SourceSpecBootstrapper", ""]
            for guideline_id in sorted(guideline_ids):
                guideline_lines.extend(
                    [
                        f"guideline {guideline_id} {{",
                        f'  title: "Auto-discovered {guideline_id}"',
                        '  category: "general"',
                        "}",
                        "",
                    ]
                )
            guidelines_dsl.write_text("\n".join(guideline_lines), encoding="utf-8")

        if self.has_source_specs():
            self._out("  ℹ️  Bootstrapped docs-meta from markdown scan")
