"""Hardcoded fallback skill registry definitions: analysis and bootstrap skills."""

from __future__ import annotations

from ..._skill_contracts import SkillDefinition

__all__ = ["_ANALYSIS_SKILLS"]

_ANALYSIS_SKILLS: dict[str, SkillDefinition] = {
    "sdd-diagnose": SkillDefinition(
        name="sdd-diagnose",
        version="1.0.0",
        category="analysis",
        description="Diagnose runtime/workspace problems with governed checks.",
        when_to_use=["failing checks", "unknown workspace failures"],
        outcomes=["policy_result", "next_actions"],
        allowed_tools=["sdd doctor run", "sdd runtime status --force"],
        cli_fallback=["sdd doctor run", "sdd runtime status --force"],
        required_permissions=["workspace-read"],
        risk_score="low",
        tags=["analysis", "runtime", "soft-governance"],
        triggers=[
            "failing",
            "error",
            "traceback",
            "root cause",
            "why",
            "what is wrong",
            "unknown failure",
            "diagnose",
            "analyze",
            "investigate",
        ],
        forbidden=[
            "modify files",
            "apply fixes",
            "run destructive commands",
            "write output",
        ],
        fallback_to=None,
        idempotent=True,
    ),
    "sdd-validate-governance": SkillDefinition(
        name="sdd-validate-governance",
        version="1.1.0",
        category="governance",
        description="Validate governance integrity and runtime preflight.",
        when_to_use=["pre-delivery gate", "compliance checks"],
        outcomes=["policy_result", "next_actions"],
        allowed_tools=["sdd governance validate", "sdd runtime status"],
        cli_fallback=["sdd governance validate", "sdd runtime status"],
        required_permissions=["workspace-read"],
        risk_score="medium",
        tags=["governance", "validation"],
        triggers=[
            "validate governance",
            "compliance check",
            "pre-delivery",
            "governance check",
            "runtime preflight",
            "fingerprint",
            "integrity check",
        ],
        forbidden=[
            "modify governance files",
            "auto-repair governance",
            "skip validation steps",
            "report ok when checks fail",
        ],
        fallback_to=None,
        idempotent=True,
        context_policy={"max_context_tokens": 1200, "default_detail": "minimal"},
    ),
    "sdd-review-architecture": SkillDefinition(
        name="sdd-review-architecture",
        version="1.0.0",
        category="architecture",
        description="Review architecture adherence against SDD mandates.",
        when_to_use=["major refactor", "architecture review"],
        outcomes=["policy_result", "next_actions"],
        allowed_tools=["sdd governance score --verbose"],
        cli_fallback=["sdd governance score --verbose"],
        required_permissions=["workspace-read"],
        risk_score="high",
        tags=["architecture", "review"],
        escalation_policy={
            "mode": "warn",
            "require_human_on": ["critical_violation", "high_risk_change"],
        },
        triggers=[
            "architecture review",
            "refactor",
            "major change",
            "design review",
            "architecture adherence",
            "mandate compliance",
            "structural assessment",
        ],
        forbidden=[
            "modify files",
            "apply fixes",
            "suggest implementation details outside declared scope",
        ],
        fallback_to="sdd-diagnose",
        idempotent=True,
    ),
    "sdd-harness": SkillDefinition(
        name="sdd-harness",
        version="1.0.0",
        category="bootstrap",
        description="Bootstrap pointer skill for file-based skill-discovery agents (Claude Code, Antigravity/Gemini CLI). Points to .sdd/agent-instructions.md as the single governance authority.",
        when_to_use=[
            "agent startup / skill discovery",
            "locating canonical governance entrypoints",
        ],
        outcomes=["bootstrap_pointer"],
        allowed_tools=["sdd runtime status"],
        cli_fallback=["sdd runtime status --force"],
        required_permissions=["workspace-read"],
        risk_score="low",
        tags=["bootstrap", "meta", "pointer"],
        triggers=["startup", "bootstrap", "skill discovery"],
        forbidden=[
            "duplicate governance authority content",
            "diverge from .sdd/agent-instructions.md",
        ],
        fallback_to=None,
        idempotent=True,
    ),
}
